"use client";
import { useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { contributorAuth, contributorLogout, saveContributorPrompt, type PromptActionResult } from "@/app/prompts/actions";
import { managePrompt } from "@/app/admin/prompts/actions";
import { type Contributor, type Prompt } from "@/lib/prompts";
import { PromptMedia } from "./library";

const fieldClass = "mt-2 w-full rounded-xl border border-outline-variant bg-background p-3 text-on-background";
const buttonClass = "rounded-full bg-primary px-5 py-3 font-semibold text-on-primary disabled:opacity-50";
export function ActionForm({ action, children, className = "space-y-4", onSuccess }: { action: (form: FormData) => Promise<PromptActionResult>; children: ReactNode; className?: string; onSuccess?: () => void }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [result, setResult] = useState<PromptActionResult | null>(null);
  return <form className={className} onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setResult(null); try { const response = await action(form); setResult(response); if (response.ok) { router.refresh(); onSuccess?.(); } } catch { setResult({ ok: false, message: "Unable to complete this action. Please retry." }); } finally { setBusy(false); } }}><fieldset disabled={busy} className="min-w-0 space-y-4">{children}</fieldset>{busy && <p role="status">Saving…</p>}{result && <p role={result.ok ? "status" : "alert"} className={`rounded-xl border p-3 text-sm ${result.ok ? "border-primary text-primary" : "border-red-400 text-red-600"}`}>{result.message}</p>}</form>;
}
function Field({ label, name, value = "", multiline = false, required = true, placeholder, type = "text", maxLength = 2000 }: { label: string; name: string; value?: string | number; multiline?: boolean; required?: boolean; placeholder?: string; type?: string; maxLength?: number }) {
  return <label className="block text-sm font-semibold">{label}{multiline ? <textarea name={name} defaultValue={value} required={required} placeholder={placeholder} maxLength={maxLength} rows={name === "template" ? 8 : 3} className={fieldClass} /> : <input name={name} defaultValue={value} required={required} placeholder={placeholder} type={type} maxLength={maxLength} min={type === "number" ? 0 : undefined} step={type === "number" ? "0.01" : undefined} className={fieldClass} />}</label>;
}
export function PromptEditor({ prompt, admin = false }: { prompt?: Prompt; admin?: boolean }) {
  return <ActionForm action={admin ? managePrompt : saveContributorPrompt}><input type="hidden" name="operation" value="save" /><input type="hidden" name="id" value={prompt?.id ?? ""} /><div className="grid gap-4 md:grid-cols-2"><Field label="Prompt title" name="title" value={prompt?.title} maxLength={140} /><Field label="Category" name="category" value={prompt?.category} placeholder="Marketing, Images, Video, Coding…" maxLength={60} /><Field label="AI model / tool" name="model" value={prompt?.model} placeholder="ChatGPT, Gemini, Midjourney…" maxLength={80} /><Field label="Price (PKR) — 0 for free" name="price" type="number" value={prompt?.price ?? 0} /></div><Field label="Description / what this prompt creates" name="description" value={prompt?.description} multiline /><Field label="Prompt template" name="template" value={prompt?.template} multiline maxLength={30000} placeholder="Write 3 Facebook ads for {{BusinessName}} targeting {{TargetAudience}}. Highlight {{Offer}} using a {{Tone}} tone." /><p className="text-sm text-on-surface-variant">Use double braces such as {"{{BusinessName}}"} for fillable variables. Fields are created automatically. Use letters, numbers, spaces or underscores in variable names.</p><Field label="Output image / video Google Drive links — one per line (up to 6)" name="media_urls" value={prompt?.media_urls.join("\n")} multiline maxLength={3100} placeholder="https://drive.google.com/file/d/FILE_ID/view" /><p className="text-sm text-on-surface-variant">Upload your output images or videos to Google Drive and set General access to “Anyone with the link”. Only links are saved here. Drive must allow the preview to be displayed.</p><Field label="Purchase / contact HTTPS link (required for paid prompts)" name="purchase_url" value={prompt?.purchase_url} required={false} type="url" maxLength={1000} />{admin && <><label className="block text-sm font-semibold">Publication status<select name="status" defaultValue={prompt?.status ?? "approved"} className={fieldClass}><option value="approved">Published</option><option value="pending">Pending review</option><option value="rejected">Rejected / hidden</option></select></label><Field label="Admin note" name="admin_note" value={prompt?.admin_note} required={false} multiline /></>}<button className={buttonClass}>{admin ? "Save prompt" : "Submit prompt"}</button></ActionForm>;
}
export function ContributorPortal({ contributor, prompts }: { contributor: Contributor | null; prompts: Prompt[] }) {
  const [mode, setMode] = useState("register");
  if (!contributor) return <div className="mx-auto max-w-xl rounded-3xl border border-outline-variant bg-surface p-6 md:p-8"><h2 className="text-2xl font-bold">{mode === "register" ? "Become a prompt contributor" : "Contributor sign in"}</h2><p className="mb-6 mt-3 text-on-surface-variant">This is a separate prompt-library account. No course enrollment is needed.</p><div className="mb-6 flex gap-4"><button onClick={() => setMode("register")} aria-pressed={mode === "register"} className={mode === "register" ? "font-bold text-primary" : ""}>Request access</button><button onClick={() => setMode("login")} aria-pressed={mode === "login"} className={mode === "login" ? "font-bold text-primary" : ""}>Sign in</button></div><ActionForm key={mode} action={contributorAuth}><input type="hidden" name="mode" value={mode} />{mode === "register" && <Field label="Your name" name="name" maxLength={100} />}<Field label="Email" name="email" type="email" maxLength={254} /><Field label="Password (at least 12 characters)" name="password" type="password" maxLength={128} />{mode === "register" && <Field label="Tell admin what kind of prompts you want to share" name="request_note" multiline />}<button className={buttonClass}>{mode === "register" ? "Send access request" : "Sign in"}</button></ActionForm></div>;
  return <div className="space-y-7"><section className="rounded-2xl border border-outline-variant bg-surface p-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-2xl font-bold">Welcome, {contributor.name}</h2><ActionForm action={contributorLogout}><button className="text-primary">Sign out</button></ActionForm></div><p className="mt-3 font-semibold">Access: {contributor.status}</p><p className="mt-2 text-on-surface-variant">{contributor.status === "approved" ? contributor.auto_publish ? "You can publish prompts directly. Admin can review and hide prompts when needed." : "You can submit prompts. Each new or edited prompt goes to admin for approval." : contributor.status === "pending" ? "Your request has been sent to admin. Check back here for approval." : "Your contributor request was declined. See the admin note below."}</p>{contributor.admin_note && <p className="mt-4 whitespace-pre-wrap rounded-xl bg-background p-4">Admin: {contributor.admin_note}</p>}</section>{contributor.status === "approved" && <section className="rounded-2xl border border-outline-variant bg-surface p-6"><h2 className="mb-5 text-2xl font-bold">Add a prompt</h2><PromptEditor /></section>}<section><h2 className="mb-4 text-2xl font-bold">Your prompts ({prompts.length})</h2>{prompts.map((prompt) => <details key={prompt.id} className="mb-4 rounded-2xl border border-outline-variant bg-surface p-5"><summary className="cursor-pointer font-bold">{prompt.title} · {prompt.status}</summary>{prompt.admin_note && <p className="my-4 whitespace-pre-wrap">Admin: {prompt.admin_note}</p>}{contributor.status === "approved" && <div className="mt-5"><PromptEditor key={`${prompt.id}-${prompt.status}`} prompt={prompt} /></div>}</details>)}</section></div>;
}
export function PromptAdmin({ contributors, prompts }: { contributors: Contributor[]; prompts: Prompt[] }) {
  const [tab, setTab] = useState("requests"); const [filter, setFilter] = useState("all");
  return <div className="space-y-6"><header><h1 className="text-3xl font-bold">Prompt library</h1><p className="mt-2 text-on-surface-variant">Manage contributor access, review prompts, and publish your own.</p></header><nav className="flex flex-wrap gap-3">{[["requests", `Contributors (${contributors.filter((c) => c.status === "pending").length} pending)`], ["prompts", `Prompts (${prompts.filter((p) => p.status === "pending").length} pending)`], ["create", "Add prompt"]].map(([id, title]) => <button key={id} onClick={() => { setTab(id); setFilter("all"); }} aria-pressed={tab === id} className={tab === id ? buttonClass : "rounded-full border border-outline-variant px-5 py-3"}>{title}</button>)}</nav>{tab !== "create" && <label className="block max-w-xs text-sm font-semibold">Filter status<select value={filter} onChange={(e) => setFilter(e.target.value)} className={fieldClass}><option value="all">All</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label>}
  {tab === "create" && <section className="rounded-2xl border border-outline-variant bg-surface p-6"><PromptEditor admin /></section>}
  {tab === "requests" && <>{!contributors.filter((c) => filter === "all" || c.status === filter).length && <p>No contributors with this status.</p>}{contributors.filter((c) => filter === "all" || c.status === filter).map((c) => <section key={c.id} className="rounded-2xl border border-outline-variant bg-surface p-6"><h2 className="text-xl font-bold">{c.name} · {c.status}</h2><p className="my-2 text-sm text-on-surface-variant">{c.email}</p><p className="mb-5 whitespace-pre-wrap">{c.request_note}</p><ActionForm action={managePrompt}><input type="hidden" name="operation" value="contributor" /><input type="hidden" name="id" value={c.id} /><label className="block">Access<select name="status" defaultValue={c.status} className={fieldClass}><option value="pending">Pending</option><option value="approved">Allow submissions</option><option value="rejected">Reject / revoke access</option></select></label><label className="flex items-center gap-3"><input type="checkbox" name="auto_publish" defaultChecked={c.auto_publish} />Allow direct publishing without per-prompt approval</label><p className="text-sm text-on-surface-variant">Revoking access stops future submissions. Review already published prompts separately to hide them.</p><Field label="Admin note to contributor" name="admin_note" value={c.admin_note} multiline required={false} /><button className={buttonClass}>Save contributor access</button></ActionForm></section>)}</>}
  {tab === "prompts" && <>{!prompts.filter((p) => filter === "all" || p.status === filter).length && <p>No prompts with this status.</p>}{prompts.filter((p) => filter === "all" || p.status === filter).map((p) => <details key={p.id} className="rounded-2xl border border-outline-variant bg-surface p-6"><summary className="cursor-pointer text-lg font-bold">{p.title} · {p.status} · {Number(p.price) ? `PKR ${p.price}` : "Free"}</summary><p className="my-4 text-sm text-on-surface-variant">Contributor: {contributors.find((c) => c.id === p.contributor_id)?.email ?? "Admin"}</p><PromptMedia urls={p.media_urls} title={p.title} /><div className="mt-6"><PromptEditor admin prompt={p} /></div></details>)}</>}
  </div>;
}
