"use client";
import { useMemo, useState } from "react";
import { drivePreview, fillPrompt, promptVariables, type Prompt } from "@/lib/prompts";

export function PromptMedia({ urls, title }: { urls: string[]; title: string }) {
  return <div className="grid gap-4 md:grid-cols-2">{urls.map((url, index) => { const preview = drivePreview(url); return preview ? <div key={`${url}-${index}`} className="overflow-hidden rounded-2xl border border-outline-variant bg-black"><iframe src={preview} title={`${title} — output preview ${index + 1}`} loading="lazy" allow="fullscreen" allowFullScreen referrerPolicy="no-referrer" className="aspect-video w-full border-0" /><a href={url} target="_blank" rel="noopener noreferrer" className="block bg-surface p-3 text-sm text-primary">Open preview in Google Drive ↗</a></div> : null; })}</div>;
}
function PromptDetail({ prompt }: { prompt: Prompt }) {
  const variables = promptVariables(prompt.template);
  const [values, setValues] = useState<Record<string, string>>({});
  const [generated, setGenerated] = useState("");
  const [message, setMessage] = useState("");
  return <article className="mt-5 space-y-6 border-t border-outline-variant pt-6">
    <PromptMedia urls={prompt.media_urls} title={prompt.title} />
    <p className="whitespace-pre-wrap text-on-surface-variant">{prompt.description}</p>
    {Number(prompt.price) > 0 ? <div className="rounded-2xl bg-primary-container p-6 text-on-primary-container"><h3 className="text-xl font-bold">Premium prompt · PKR {Number(prompt.price).toLocaleString()}</h3><p className="my-3">Purchase and delivery are handled by the creator through the link below.</p><a href={prompt.purchase_url} target="_blank" rel="noopener noreferrer" className="inline-block rounded-full bg-primary px-6 py-3 font-bold text-on-primary">Get this prompt ↗</a></div> : <>
    <form onSubmit={(event) => { event.preventDefault(); setGenerated(fillPrompt(prompt.template, values)); setMessage(""); }} className="rounded-2xl border border-outline-variant bg-background p-5 md:p-7"><h3 className="mb-5 text-lg font-bold">{variables.length ? "Fill in the variables" : "Ready to create?"}</h3><div className="grid gap-4 md:grid-cols-2">{variables.map((key) => <label key={key} className="text-sm font-semibold">{key.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/_/g, " ")}<input required maxLength={2000} value={values[key] ?? ""} onChange={(e) => { setValues({ ...values, [key]: e.target.value }); setGenerated(""); setMessage(""); }} placeholder={`e.g. ${key.replace(/([a-z])([A-Z])/g, "$1 $2")}`} className="mt-2 w-full rounded-xl border border-outline-variant bg-surface p-3 font-normal" /></label>)}</div><button className="mt-5 rounded-full bg-primary px-6 py-3 font-bold text-on-primary">✧ Generate prompt</button></form>
    <section><h3 className="mb-3 text-lg font-bold">{generated ? "Your personalized prompt" : "Prompt template"}</h3><div className="rounded-2xl border border-outline-variant bg-background p-5"><pre className="whitespace-pre-wrap break-words font-mono text-sm leading-7">{generated || prompt.template}</pre><button type="button" onClick={async () => { try { await navigator.clipboard.writeText(generated || prompt.template); setMessage("Prompt copied!"); } catch { setMessage("Copy unavailable. Select the prompt text above and copy it manually."); } }} className="mt-5 rounded-full bg-primary px-6 py-3 font-bold text-on-primary">Copy {generated ? "prompt" : "template"}</button><p role="status" className="mt-2 text-sm">{message}</p></div></section></>}
  </article>;
}
export function PromptLibrary({ prompts }: { prompts: Prompt[] }) {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [pricing, setPricing] = useState(""); const [sort, setSort] = useState("newest"); const [selected, setSelected] = useState<string | null>(null);
  const categories = [...new Set(prompts.map((p) => p.category))].sort();
  const filtered = useMemo(() => prompts.filter((p) => `${p.title} ${p.description} ${p.category} ${p.model}`.toLowerCase().includes(search.toLowerCase()) && (!category || p.category === category) && (!pricing || (pricing === "free" ? Number(p.price) === 0 : Number(p.price) > 0))).sort((a, b) => sort === "title" ? a.title.localeCompare(b.title) : new Date(b.created_at).getTime() - new Date(a.created_at).getTime()), [prompts, search, category, pricing, sort]);
  const field = "rounded-xl border border-outline-variant bg-surface p-3";
  return <><div className="grid gap-3 rounded-2xl bg-surface p-4 shadow-sm md:grid-cols-[2fr_1fr_1fr_1fr]"><input aria-label="Search prompts" placeholder="Search prompts, ideas, or AI models…" value={search} onChange={(e) => setSearch(e.target.value)} className={field} /><select aria-label="Category" value={category} onChange={(e) => setCategory(e.target.value)} className={field}><option value="">All categories</option>{categories.map((c) => <option key={c}>{c}</option>)}</select><select aria-label="Pricing" value={pricing} onChange={(e) => setPricing(e.target.value)} className={field}><option value="">Free & premium</option><option value="free">Free</option><option value="paid">Premium</option></select><select aria-label="Sort prompts" value={sort} onChange={(e) => setSort(e.target.value)} className={field}><option value="newest">Newest first</option><option value="title">Title A–Z</option></select></div><p className="my-6 text-sm text-on-surface-variant">{filtered.length} {filtered.length === 1 ? "prompt" : "prompts"} to explore</p>
    {!filtered.length && <div className="rounded-2xl border border-dashed border-outline-variant p-12 text-center"><h2 className="text-xl font-bold">{prompts.length ? "No matching prompts" : "Fresh ideas are on their way"}</h2><p className="mt-2 text-on-surface-variant">{prompts.length ? "Try a different search or clear your filters." : "Approved community prompts will appear here."}</p>{prompts.length > 0 && <button onClick={() => { setSearch(""); setCategory(""); setPricing(""); }} className="mt-4 text-primary">Clear filters</button>}</div>}
    <div className="grid items-start gap-5 md:grid-cols-2 lg:grid-cols-3">{filtered.map((prompt) => <div key={prompt.id} className={`rounded-3xl border border-outline-variant bg-surface p-6 shadow-sm ${selected === prompt.id ? "md:col-span-2 lg:col-span-3" : ""}`}><div className="flex items-center justify-between gap-3 text-xs font-bold"><span className="rounded-full bg-secondary-container px-3 py-1 text-on-secondary-container">{prompt.category}</span><span className="text-primary">{Number(prompt.price) === 0 ? "FREE" : `PKR ${Number(prompt.price).toLocaleString()}`}</span></div><h2 className="mb-2 mt-5 text-2xl font-bold">{prompt.title}</h2><p className="text-sm text-on-surface-variant">{prompt.model}</p>{selected !== prompt.id && <p className="mt-4 line-clamp-3 text-on-surface-variant">{prompt.description}</p>}<button aria-expanded={selected === prompt.id} onClick={() => setSelected(selected === prompt.id ? null : prompt.id)} className="mt-6 font-bold text-primary">{selected === prompt.id ? "Close prompt ↑" : "Explore prompt →"}</button>{selected === prompt.id && <PromptDetail prompt={prompt} />}</div>)}</div></>;
}
