/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './lib/**/*.{js,ts,jsx,tsx}',
    './public/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--wc-bg)',
        surface: 'var(--wc-surface)',
        'surface-low': 'var(--wc-surface-low)',
        'surface-lowest': 'var(--wc-surface-lowest)',
        'surface-container': 'var(--wc-surface-container)',
        'surface-container-low': 'var(--wc-surface-low)',
        'surface-container-lowest': 'var(--wc-surface-lowest)',
        'surface-container-high': 'var(--wc-surface-container-high)',
        'surface-variant': 'var(--wc-surface-variant)',
        'on-background': 'var(--wc-on-bg)',
        'on-surface': 'var(--wc-on-surface)',
        'on-surface-variant': 'var(--wc-on-surface-variant)',
        primary: 'var(--wc-primary)',
        'primary-container': 'var(--wc-primary-container)',
        'on-primary': 'var(--wc-on-primary)',
        'on-primary-container': 'var(--wc-on-primary-container)',
        'primary-fixed': 'var(--wc-primary-container)',
        'on-primary-fixed': 'var(--wc-on-primary)',
        secondary: 'var(--wc-secondary)',
        'secondary-container': 'var(--wc-secondary-container)',
        'on-secondary': 'var(--wc-on-secondary)',
        'on-secondary-fixed': 'var(--wc-on-secondary)',
        outline: 'var(--wc-outline)',
        'outline-variant': 'var(--wc-outline-variant)',
        error: 'var(--wc-error)',
        'error-container': 'var(--wc-error-container)',
        'on-error-container': 'var(--wc-error)',
        action: 'var(--wc-primary-container)',
      },
      boxShadow: {
        card: '0 8px 24px rgba(2, 33, 110, 0.06)',
        'card-hover': '0 12px 40px rgba(2, 33, 110, 0.08)',
        glow: '0 10px 30px rgba(0, 33, 110, 0.14)',
        'glow-lg': '0 20px 60px rgba(0, 33, 110, 0.18)',
        'inner-light': 'inset 0 1px 2px rgba(0, 0, 0, 0.03)',
      },
      fontSize: {
        'body-sm': ['0.875rem', { lineHeight: '1.4' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.06em', fontWeight: '700' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem', fontWeight: '700' }],
        'title-lg': ['1.125rem', { lineHeight: '1.5rem', fontWeight: '700' }],
        'headline-lg': ['2rem', { lineHeight: '2.35rem', fontWeight: '800' }],
      },
      maxWidth: {
        'container-max': '1180px',
      },
      spacing: {
        'margin-page': 'clamp(1.25rem, 4vw, 4rem)',
        xxl: '6rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
