-- 50 projects each for four AI courses (200 projects total).
-- Content, Graphic Design, Office: 25 Intermediate + 25 Advanced.
-- Kids: 25 Beginner + 25 Intermediate (age-appropriate progression).
-- Paste into Supabase SQL Editor and Run. Duplicate-safe by course + title.

begin;
do $$
declare
  content_id uuid; design_id uuid; kids_id uuid; office_id uuid;
  content_count int; design_count int; kids_count int; office_count int;
begin
  select id into content_id from public.courses where lower(btrim(title))=lower('AI for Content Creation & YouTube Automation') order by created_at limit 1;
  select id into design_id from public.courses where lower(btrim(title))=lower('AI for Graphic Design (Canva & Tools)') order by created_at limit 1;
  select id into kids_id from public.courses where lower(btrim(title))=lower('AI for Kids & Beginners (Fun Learning)') order by created_at limit 1;
  select id into office_id from public.courses where lower(btrim(title))=lower('AI for Office Management & Productivity') order by created_at limit 1;
  if content_id is null then raise exception 'Content Creation course not found'; end if;
  if design_id is null then raise exception 'Graphic Design course not found'; end if;
  if kids_id is null then raise exception 'Kids course not found'; end if;
  if office_id is null then raise exception 'Office Productivity course not found'; end if;

  with x as (select title,ordinality n from unnest(array[
    '[Intermediate] Faceless YouTube Channel Launch','[Intermediate] 30-Day Short-Form Video Series','[Intermediate] Educational Explainer Video Channel','[Intermediate] Podcast-to-Content Repurposing System','[Intermediate] AI-Assisted YouTube Script Portfolio','[Intermediate] Product Review Video Campaign','[Intermediate] Personal Brand Content Calendar','[Intermediate] Documentary Storytelling Project','[Intermediate] YouTube SEO Optimization Sprint','[Intermediate] Automated Thumbnail Testing Plan','[Intermediate] Multi-Platform Content Repurposing','[Intermediate] AI Voiceover Video Production','[Intermediate] Interview Clips Content Engine','[Intermediate] E-commerce Video Ads Campaign','[Intermediate] Local Business YouTube Strategy','[Intermediate] News Summary Channel Workflow','[Intermediate] Animated Facts Channel Project','[Intermediate] Course Lesson Video Production','[Intermediate] Travel Content Automation Plan','[Intermediate] Recipe Video Content Series','[Intermediate] LinkedIn Thought Leadership System','[Intermediate] Newsletter-to-Video Workflow','[Intermediate] Audience Research and Idea Bank','[Intermediate] Content Quality Review Framework','[Intermediate] YouTube Analytics Growth Report',
    '[Advanced] AI YouTube Automation Studio','[Advanced] Multi-Channel Media Operations Platform','[Advanced] Long-Form Documentary Production Pipeline','[Advanced] Multilingual Video Localization System','[Advanced] AI-Powered Content Research Desk','[Advanced] Brand-Safe Generative Content Factory','[Advanced] Automated Podcast Production Network','[Advanced] YouTube Revenue Optimization Strategy','[Advanced] AI Avatar Training Video Platform','[Advanced] Real-Time Trend Response Newsroom','[Advanced] Enterprise Video Knowledge Academy','[Advanced] Creator Sponsorship Operations System','[Advanced] Data-Driven Thumbnail Experiment Lab','[Advanced] Personalized Video Marketing Funnel','[Advanced] Content Rights and Attribution Workflow','[Advanced] AI Fact-Checking Editorial Pipeline','[Advanced] Interactive Shoppable Video Campaign','[Advanced] Global Short-Form Content Network','[Advanced] YouTube Community Growth Engine','[Advanced] AI Content Governance Framework','[Advanced] Sports Highlights Editorial Workflow','[Advanced] Automated Webinar Repurposing Platform','[Advanced] Creator Analytics Executive Dashboard','[Advanced] Scalable Content Team Operating System','[Advanced] Capstone AI Media Company Launch'
  ]::text[]) with ordinality t(title,ordinality))
  insert into public.course_projects(course_id,title,description)
  select content_id,title,case when n<=25 then 'Produce '||replace(title,'[Intermediate] ','')||' using an ethical AI-assisted workflow. Define audience, niche, goals and brand voice; research topics, create original scripts, visuals, voice or captions, and publish a polished sample set. Apply copyright, disclosure and fact-checking rules, optimize titles/thumbnails/SEO, track retention and engagement, and submit source files, prompts, analytics evidence and an improvement report.' else 'Design '||replace(title,'[Advanced] ','')||' as a scalable professional media operation. Combine human editorial control with AI research, scripting, production, localization, distribution and analytics. Implement brand-safety, copyright, source verification, approval gates, reusable templates, automation, cost controls and KPI experiments. Deliver production assets, workflow maps, governance documentation and a data-backed growth strategy.' end from x p
  where not exists(select 1 from public.course_projects e where e.course_id=content_id and lower(btrim(e.title))=lower(btrim(p.title)));
  get diagnostics content_count=row_count;

  with x as (select title,ordinality n from unnest(array[
    '[Intermediate] Complete Startup Brand Kit','[Intermediate] Social Media Campaign Design Set','[Intermediate] Restaurant Visual Identity','[Intermediate] E-commerce Product Ad Creatives','[Intermediate] Professional Presentation Design','[Intermediate] YouTube Thumbnail Portfolio','[Intermediate] Event Promotion Design Pack','[Intermediate] Real Estate Marketing Templates','[Intermediate] Personal Brand Media Kit','[Intermediate] Nonprofit Awareness Campaign','[Intermediate] Mobile App UI Concept','[Intermediate] Infographic Data Storytelling','[Intermediate] Packaging Design Concept','[Intermediate] Book Cover Design Series','[Intermediate] Email Newsletter Template Kit','[Intermediate] LinkedIn Carousel Campaign','[Intermediate] Wedding Invitation Design Suite','[Intermediate] Educational Worksheet Collection','[Intermediate] Podcast Visual Branding','[Intermediate] Fashion Lookbook Design','[Intermediate] Travel Brochure Campaign','[Intermediate] Resume and Portfolio Design','[Intermediate] Animated Social Post Collection','[Intermediate] AI Image Prompt Style Library','[Intermediate] Accessible Design Audit Project',
    '[Advanced] AI-Powered Brand Design System','[Advanced] Enterprise Multi-Brand Template Library','[Advanced] Generative Advertising Creative Lab','[Advanced] Data-Driven Creative Testing Campaign','[Advanced] Global Multilingual Design System','[Advanced] AI Product Photography Studio','[Advanced] Dynamic Personalized Ad System','[Advanced] Editorial Magazine Design Platform','[Advanced] Complete SaaS Product Launch Identity','[Advanced] Motion Graphics Campaign Suite','[Advanced] Ethical Generative Art Exhibition','[Advanced] AI Fashion Campaign Production','[Advanced] Retail Packaging and Mockup System','[Advanced] Enterprise Presentation Automation','[Advanced] Social Media Design Operations Hub','[Advanced] Design Accessibility Governance Kit','[Advanced] Visual Content Localization Factory','[Advanced] AI Character and Mascot System','[Advanced] Omnichannel Festival Campaign','[Advanced] Luxury Brand Identity Program','[Advanced] AI Interior Visualization Portfolio','[Advanced] Creator Merchandise Design System','[Advanced] Design Performance Analytics Report','[Advanced] Agency Client Template Portal','[Advanced] Capstone AI Creative Agency Launch'
  ]::text[]) with ordinality t(title,ordinality))
  insert into public.course_projects(course_id,title,description)
  select design_id,title,case when n<=25 then 'Create '||replace(title,'[Intermediate] ','')||' with Canva and suitable AI design tools. Begin with a client brief, audience research, moodboard, color/type system and original prompt plan. Produce consistent assets in required sizes, check hierarchy, contrast, accessibility and licensing, document revisions, and submit editable source links, exports, mockups and a rationale explaining every major design decision.' else 'Lead '||replace(title,'[Advanced] ','')||' as a professional creative-system project. Build reusable brand rules, components and templates; use generative tools with human art direction, provenance and rights checks; support multiple formats and channels; test creative variants against KPIs; and enforce accessibility and review workflows. Deliver an organized asset library, governance guide, campaign mockups and client-ready case study.' end from x p
  where not exists(select 1 from public.course_projects e where e.course_id=design_id and lower(btrim(e.title))=lower(btrim(p.title)));
  get diagnostics design_count=row_count;

  with x as (select title,ordinality n from unnest(array[
    '[Beginner] AI Storybook with Original Characters','[Beginner] My Dream City Poster','[Beginner] Animal Facts Presentation','[Beginner] Space Adventure Comic','[Beginner] Healthy Habits Quiz','[Beginner] AI Vocabulary Flashcards','[Beginner] Weather Reporter Project','[Beginner] Kindness Campaign Poster','[Beginner] Build a Simple Chatbot Plan','[Beginner] Dinosaur Research Booklet','[Beginner] Math Puzzle Creator','[Beginner] World Cultures Scrapbook','[Beginner] Save the Planet Campaign','[Beginner] My Future Career Presentation','[Beginner] AI-Assisted Poem Collection','[Beginner] Science Experiment Guide','[Beginner] School Event Invitation','[Beginner] Invent a Helpful Robot','[Beginner] Online Safety Superhero Comic','[Beginner] Music Playlist Cover Project','[Beginner] Daily Study Planner','[Beginner] Local History Timeline','[Beginner] Food Chain Infographic','[Beginner] Emotion and Empathy Cards','[Beginner] Fact or Fiction AI Challenge',
    '[Intermediate] Interactive Learning Quiz Show','[Intermediate] AI-Assisted School Magazine','[Intermediate] Beginner Game Design Document','[Intermediate] Community Problem Solution Pitch','[Intermediate] Educational YouTube Video','[Intermediate] Mini Science Fair Research Project','[Intermediate] Choose-Your-Own Adventure Story','[Intermediate] Student Podcast Episode','[Intermediate] Responsible AI Classroom Guide','[Intermediate] Personal Learning Tutor Prompts','[Intermediate] Coding Concept Comic Series','[Intermediate] Virtual Museum Exhibition','[Intermediate] Sustainable School Design','[Intermediate] AI Bias Detection Activity','[Intermediate] Cyber Safety Awareness Campaign','[Intermediate] Collaborative Digital Storybook','[Intermediate] Data Charts from Class Survey','[Intermediate] Language Learning Activity Pack','[Intermediate] Young Entrepreneur Business Pitch','[Intermediate] Accessibility-Friendly Poster Set','[Intermediate] AI Hallucination Investigation','[Intermediate] Classroom FAQ Chatbot Prototype','[Intermediate] Global Goals Research Presentation','[Intermediate] Digital Citizenship Portfolio','[Intermediate] Capstone Fun Learning Showcase'
  ]::text[]) with ordinality t(title,ordinality))
  insert into public.course_projects(course_id,title,description)
  select kids_id,title,case when n<=25 then 'Complete '||replace(title,'[Beginner] ','')||' through safe, guided and creative AI use. Ask an adult or teacher before using online tools, never share private information, verify important facts in trusted learning sources, and create mostly original work. Submit the finished project, a simple list of prompts/sources and a short reflection describing what the student created and what AI helped with.' else 'Develop '||replace(title,'[Intermediate] ','')||' as a supervised learning project. Plan the goal, research with two or more trusted sources, use AI for ideas rather than copying, check facts and bias, protect personal information and revise the output in the student''s own voice. Present the final artifact, process evidence, source list and a reflection on responsible AI use.' end from x p
  where not exists(select 1 from public.course_projects e where e.course_id=kids_id and lower(btrim(e.title))=lower(btrim(p.title)));
  get diagnostics kids_count=row_count;

  with x as (select title,ordinality n from unnest(array[
    '[Intermediate] AI-Assisted Meeting Minutes System','[Intermediate] Smart Email Response Library','[Intermediate] Weekly Management Report Automation','[Intermediate] Employee Onboarding Checklist','[Intermediate] Office Document Template Pack','[Intermediate] AI Presentation Creation Workflow','[Intermediate] Customer Inquiry Tracking Sheet','[Intermediate] Smart Calendar Management Plan','[Intermediate] Invoice and Expense Tracker','[Intermediate] Standard Operating Procedure Builder','[Intermediate] Recruitment Interview Kit','[Intermediate] Project Status Dashboard','[Intermediate] Inventory Reorder Workbook','[Intermediate] AI Research and Briefing Report','[Intermediate] Team Task Prioritization System','[Intermediate] Business Travel Planning Pack','[Intermediate] Performance Review Template System','[Intermediate] Office Knowledge Base Setup','[Intermediate] Data Cleanup and Validation Workbook','[Intermediate] Client Proposal Generation Kit','[Intermediate] Training Manual Development','[Intermediate] Survey Analysis and Report','[Intermediate] Professional Email Campaign','[Intermediate] Workplace Policy Summary Project','[Intermediate] Productivity Improvement Audit',
    '[Advanced] AI Executive Assistant Operating System','[Advanced] Enterprise Knowledge Management Hub','[Advanced] Intelligent Document Processing Workflow','[Advanced] Automated Management Reporting Suite','[Advanced] AI-Powered Recruitment Operations','[Advanced] Cross-Department Approval System','[Advanced] Predictive Workforce Planning Dashboard','[Advanced] Enterprise Meeting Intelligence Platform','[Advanced] AI Customer Operations Command Center','[Advanced] Financial Planning and Variance System','[Advanced] Contract Review and Obligation Tracker','[Advanced] Multi-Office Resource Scheduling','[Advanced] Business Continuity Management System','[Advanced] AI Procurement Analysis Platform','[Advanced] Secure Board Reporting Workflow','[Advanced] Employee Service Desk Automation','[Advanced] Compliance Evidence Management Hub','[Advanced] Data Governance Office Toolkit','[Advanced] AI Sales Operations Workspace','[Advanced] Organization-Wide KPI Architecture','[Advanced] Executive Decision Support Dashboard','[Advanced] Digital Transformation Roadmap','[Advanced] Privacy-First Office AI Policy','[Advanced] Office Automation ROI Assessment','[Advanced] Capstone AI-Enabled Smart Office'
  ]::text[]) with ordinality t(title,ordinality))
  insert into public.course_projects(course_id,title,description)
  select office_id,title,case when n<=25 then 'Build '||replace(title,'[Intermediate] ','')||' using appropriate office and AI productivity tools. Define the business problem, users, inputs and approval owner; create reusable templates, validated data and a documented workflow; protect confidential information; manually verify AI-generated content; and submit working files, sample outputs, instructions and measurable time/quality improvements.' else 'Design '||replace(title,'[Advanced] ','')||' as an enterprise-ready productivity solution. Map stakeholders, controls, data classification, approval stages and KPIs; combine AI assistance with human accountability, integrations and automation; address privacy, security, retention, accessibility and change management; and deliver prototypes, governance documentation, training material, risk analysis and a quantified ROI report.' end from x p
  where not exists(select 1 from public.course_projects e where e.course_id=office_id and lower(btrim(e.title))=lower(btrim(p.title)));
  get diagnostics office_count=row_count;

  raise notice 'Inserted Content %, Design %, Kids %, Office % projects.',content_count,design_count,kids_count,office_count;
end $$;
commit;

select c.title course,count(cp.id) total_projects,
 count(cp.id) filter(where cp.title like '[Beginner]%') beginner,
 count(cp.id) filter(where cp.title like '[Intermediate]%') intermediate,
 count(cp.id) filter(where cp.title like '[Advanced]%') advanced
from public.courses c left join public.course_projects cp on cp.course_id=c.id
where lower(btrim(c.title)) in (lower('AI for Content Creation & YouTube Automation'),lower('AI for Graphic Design (Canva & Tools)'),lower('AI for Kids & Beginners (Fun Learning)'),lower('AI for Office Management & Productivity'))
group by c.id,c.title order by c.title;
