-- Tops up the six named courses to exactly 50 catalog projects each.
-- Candidate 1-25 = Intermediate, 26-50 = Advanced.
-- Existing projects are preserved; only enough missing candidates are inserted to reach 50.
-- Paste the complete file into Supabase SQL Editor and click Run.

begin;
do $$
begin
create temporary table project_seed(course_title text, seq int, title text, focus text) on commit drop;

insert into project_seed
select 'AI for Students & Freelancers', n, title, 'student and freelance career growth'
from unnest(array[
'[Intermediate] AI Study Planner and Revision Coach','[Intermediate] Smart Assignment Research Workflow','[Intermediate] Freelance Profile Optimization','[Intermediate] AI Proposal Writing Portfolio','[Intermediate] Client Brief Analysis Toolkit','[Intermediate] Personal Portfolio Content System','[Intermediate] AI Presentation Production Project','[Intermediate] Academic Notes Summarization Workflow','[Intermediate] Job Application Assistant Kit','[Intermediate] Freelance Pricing Calculator','[Intermediate] Social Media Personal Brand Plan','[Intermediate] AI Language Learning Routine','[Intermediate] Client Meeting Preparation System','[Intermediate] Research Source Verification Project','[Intermediate] AI Resume and Cover Letter Pack','[Intermediate] Time Management Dashboard','[Intermediate] Online Course Creation Plan','[Intermediate] Freelance Invoice and Tracker','[Intermediate] AI Interview Practice System','[Intermediate] Digital Product Launch Project','[Intermediate] Client Email Template Library','[Intermediate] Skill Gap Analysis Roadmap','[Intermediate] AI Content Repurposing Workflow','[Intermediate] Remote Work Productivity System','[Intermediate] Freelance Case Study Portfolio',
'[Advanced] AI-Powered Freelance Agency System','[Advanced] Multi-Client Project Operations Hub','[Advanced] AI Lead Generation and Qualification','[Advanced] Automated Proposal and Contract Pipeline','[Advanced] Personal Knowledge Management Platform','[Advanced] AI Research Consultancy Project','[Advanced] Freelance Revenue Analytics Dashboard','[Advanced] Client Onboarding Automation','[Advanced] AI Course Business Launch','[Advanced] Global Remote Career Strategy','[Advanced] Multi-Agent Learning Assistant','[Advanced] AI Digital Product Factory','[Advanced] Freelancer CRM and Retention System','[Advanced] Ethical AI Academic Research Framework','[Advanced] AI Portfolio Evaluation Platform','[Advanced] Marketplace Gig Optimization Lab','[Advanced] Automated Client Reporting System','[Advanced] AI Scholarship Discovery Workflow','[Advanced] Student Startup Validation Project','[Advanced] Freelance Team Collaboration System','[Advanced] AI Career Intelligence Dashboard','[Advanced] Subscription Service Business Model','[Advanced] Cross-Platform Creator Workflow','[Advanced] Data-Driven Freelance Growth Strategy','[Advanced] Capstone AI-Enabled Freelance Business'
]::text[]) with ordinality t(title,n);

insert into project_seed
select 'AI Productivity & Automation Mastery', n, title, 'AI productivity and business process automation'
from unnest(array[
'[Intermediate] Smart Daily Planning Workflow','[Intermediate] AI Email Management System','[Intermediate] Meeting Notes to Tasks Automation','[Intermediate] Document Summarization Pipeline','[Intermediate] Automated Weekly Report Builder','[Intermediate] Calendar Scheduling Assistant','[Intermediate] Personal Knowledge Base Setup','[Intermediate] AI Spreadsheet Analysis Project','[Intermediate] Repetitive Task Automation Audit','[Intermediate] Smart File Organization Workflow','[Intermediate] Form to Database Automation','[Intermediate] AI Presentation Generator','[Intermediate] Customer Follow-Up Workflow','[Intermediate] Invoice Reminder Automation','[Intermediate] Content Calendar Automation','[Intermediate] Team Notification System','[Intermediate] AI SOP Creation Toolkit','[Intermediate] Lead Capture and Routing Flow','[Intermediate] Productivity Metrics Dashboard','[Intermediate] Automated Data Cleanup Pipeline','[Intermediate] AI Research Brief Generator','[Intermediate] Employee Onboarding Automation','[Intermediate] Approval Request Workflow','[Intermediate] Multi-App Task Synchronization','[Intermediate] Personal Productivity Command Center',
'[Advanced] Enterprise AI Productivity Platform','[Advanced] Multi-Agent Operations Assistant','[Advanced] Intelligent Document Processing System','[Advanced] Human-in-the-Loop Approval Engine','[Advanced] AI Executive Assistant Workspace','[Advanced] Cross-Department Automation Architecture','[Advanced] Enterprise Knowledge Retrieval System','[Advanced] Automated Compliance Reporting','[Advanced] AI Customer Operations Workflow','[Advanced] Predictive Workload Planning System','[Advanced] Secure Contract Review Automation','[Advanced] Revenue Operations Automation Hub','[Advanced] AI Procurement Workflow','[Advanced] Intelligent HR Operations Platform','[Advanced] Event-Driven Business Automation','[Advanced] Resilient Multi-App Integration System','[Advanced] AI Quality Assurance Pipeline','[Advanced] Automated Management Dashboard','[Advanced] Privacy-First Workplace AI System','[Advanced] Business Continuity Automation','[Advanced] AI Workflow Cost Optimization','[Advanced] Enterprise Automation Governance','[Advanced] Scalable Queue-Based Automation','[Advanced] Automation ROI and Analytics Platform','[Advanced] Capstone Autonomous Business Operations'
]::text[]) with ordinality t(title,n);

insert into project_seed
select 'Botpress Chatbot Development', n, title, 'Botpress conversational AI development'
from unnest(array[
'[Intermediate] Website FAQ Support Bot','[Intermediate] Restaurant Reservation Chatbot','[Intermediate] E-commerce Product Assistant','[Intermediate] Student Admission Help Bot','[Intermediate] Appointment Booking Chatbot','[Intermediate] Real Estate Inquiry Bot','[Intermediate] Lead Qualification Chatbot','[Intermediate] Event Registration Assistant','[Intermediate] Hotel Guest Support Bot','[Intermediate] Clinic Information Chatbot','[Intermediate] Course Recommendation Bot','[Intermediate] Order Tracking Assistant','[Intermediate] Employee Onboarding Bot','[Intermediate] Insurance FAQ Chatbot','[Intermediate] Travel Planning Assistant','[Intermediate] Multilingual Customer Support Bot','[Intermediate] Feedback Collection Chatbot','[Intermediate] Banking Information Assistant','[Intermediate] Job Application Help Bot','[Intermediate] Fitness Coaching Chatbot','[Intermediate] Product Troubleshooting Bot','[Intermediate] Survey and Quiz Chatbot','[Intermediate] WhatsApp Lead Capture Bot','[Intermediate] Knowledge Base Search Bot','[Intermediate] Human Agent Handoff Bot',
'[Advanced] Enterprise RAG Support Assistant','[Advanced] Multi-Tenant Customer Service Bot','[Advanced] AI Sales Qualification Platform','[Advanced] Omnichannel Commerce Assistant','[Advanced] Healthcare Intake Chatbot','[Advanced] Financial Services Compliance Bot','[Advanced] Multi-Agent Travel Concierge','[Advanced] HR Policy and Service Desk Bot','[Advanced] Voice-Enabled Booking Assistant','[Advanced] Personalized Learning Tutor Bot','[Advanced] Contract Knowledge Assistant','[Advanced] Incident Response ChatOps Bot','[Advanced] Intelligent Ticket Triage System','[Advanced] Multilingual Global Support Platform','[Advanced] Customer Retention and Churn Bot','[Advanced] Bot Analytics and Evaluation Suite','[Advanced] Secure Identity-Verified Chatbot','[Advanced] Dynamic Workflow Orchestration Bot','[Advanced] AI Recruitment Interview Assistant','[Advanced] Property Sales Conversation Platform','[Advanced] Conversation Quality Monitoring System','[Advanced] Resilient API-Integrated Assistant','[Advanced] Generative UI Chat Experience','[Advanced] Enterprise Bot Governance Framework','[Advanced] Capstone Production Botpress Platform'
]::text[]) with ordinality t(title,n);

insert into project_seed
select 'Certified Research Methodology & Consultancy Training', n, title, 'professional research methodology and consultancy'
from unnest(array[
'[Intermediate] Quantitative Survey Research Project','[Intermediate] Qualitative Interview Study','[Intermediate] Mixed-Methods Research Proposal','[Intermediate] Systematic Literature Review','[Intermediate] Market Research Consultancy Brief','[Intermediate] Customer Satisfaction Study','[Intermediate] Employee Engagement Research','[Intermediate] Competitor Benchmarking Report','[Intermediate] Focus Group Research Project','[Intermediate] Case Study Research Design','[Intermediate] Research Questionnaire Validation','[Intermediate] Sampling Strategy Project','[Intermediate] Data Cleaning and Codebook','[Intermediate] Descriptive Statistics Report','[Intermediate] Research Ethics Application','[Intermediate] Academic Referencing Audit','[Intermediate] Policy Research Brief','[Intermediate] Feasibility Study Project','[Intermediate] Needs Assessment Consultancy','[Intermediate] Program Evaluation Plan','[Intermediate] Social Media Research Study','[Intermediate] User Experience Research Project','[Intermediate] Interview Thematic Analysis','[Intermediate] Research Presentation and Poster','[Intermediate] Client Research Recommendations',
'[Advanced] Longitudinal Impact Evaluation','[Advanced] Experimental Research Design','[Advanced] Advanced Mixed-Methods Study','[Advanced] Meta-Analysis Research Project','[Advanced] National Market Intelligence Report','[Advanced] Causal Inference Consultancy Study','[Advanced] Predictive Research Analytics','[Advanced] Multi-Site Program Evaluation','[Advanced] Research Quality Assurance Framework','[Advanced] Enterprise Customer Insights Program','[Advanced] Public Policy Impact Assessment','[Advanced] Healthcare Outcomes Research','[Advanced] Education Intervention Evaluation','[Advanced] International Development Baseline Study','[Advanced] Advanced Econometric Analysis','[Advanced] Research Data Governance Plan','[Advanced] AI-Assisted Evidence Synthesis','[Advanced] Ethical AI Research Audit','[Advanced] Consultancy Stakeholder Management Plan','[Advanced] Research Commercialization Strategy','[Advanced] Institutional Research Dashboard','[Advanced] Delphi Expert Consensus Study','[Advanced] Crisis and Risk Research Project','[Advanced] Executive Consultancy Report','[Advanced] Capstone End-to-End Consulting Engagement'
]::text[]) with ordinality t(title,n);

insert into project_seed
select 'Develop .NET applications', n, title, '.NET application engineering'
from unnest(array[
'[Intermediate] ASP.NET Core Task Management API','[Intermediate] Blazor Employee Directory','[Intermediate] Entity Framework Inventory System','[Intermediate] MVC E-commerce Starter','[Intermediate] JWT Authentication Service','[Intermediate] Clinic Appointment Application','[Intermediate] Library Management System','[Intermediate] Expense Tracking Web API','[Intermediate] SignalR Real-Time Chat','[Intermediate] Background Email Worker','[Intermediate] File Upload Document Portal','[Intermediate] Role-Based Admin Dashboard','[Intermediate] Restaurant Ordering System','[Intermediate] Student Enrollment Application','[Intermediate] Customer Support Ticket API','[Intermediate] Redis-Cached Product Catalog','[Intermediate] Automated Testing Practice API','[Intermediate] Logging and Monitoring Dashboard','[Intermediate] Payment Sandbox Integration','[Intermediate] Multi-Language Content Website','[Intermediate] Hangfire Scheduled Jobs System','[Intermediate] GraphQL Product Service','[Intermediate] Dockerized .NET Application','[Intermediate] Azure Blob File Manager','[Intermediate] Clean Architecture Project Starter',
'[Advanced] Multi-Tenant SaaS with ASP.NET Core','[Advanced] Event-Driven Commerce Microservices','[Advanced] CQRS and Event Sourcing Platform','[Advanced] Enterprise Identity and Access Service','[Advanced] High-Scale SignalR Notification Hub','[Advanced] gRPC Service Communication Platform','[Advanced] .NET AI Document Intelligence API','[Advanced] Cloud-Native Banking Ledger','[Advanced] Kubernetes-Deployed .NET Platform','[Advanced] Zero-Downtime Deployment Pipeline','[Advanced] Distributed Workflow Orchestrator','[Advanced] Advanced Observability with OpenTelemetry','[Advanced] Secure Healthcare Records Platform','[Advanced] Multi-Region Resilient Web API','[Advanced] Real-Time Financial Processing System','[Advanced] Modular Monolith Business Platform','[Advanced] API Gateway and Rate Limit Service','[Advanced] Enterprise Search with AI Integration','[Advanced] Advanced Testing and Contract Suite','[Advanced] Serverless Azure Functions Platform','[Advanced] Message-Driven Logistics System','[Advanced] IdentityServer Security Architecture','[Advanced] Performance Engineering Lab','[Advanced] Legacy .NET Modernization Project','[Advanced] Capstone Enterprise .NET Ecosystem'
]::text[]) with ordinality t(title,n);

insert into project_seed
select 'Develop LLM-Powered Applications', n, title, 'production LLM application engineering'
from unnest(array[
'[Intermediate] Document Question Answering Assistant','[Intermediate] AI Customer Support Prototype','[Intermediate] Structured Resume Parser','[Intermediate] Meeting Summary and Action Extractor','[Intermediate] Product Recommendation Chatbot','[Intermediate] Natural Language SQL Assistant','[Intermediate] AI Content Brief Generator','[Intermediate] Semantic Search Application','[Intermediate] Prompt Template Management API','[Intermediate] Citation-Based Research Assistant','[Intermediate] AI Email Classification Service','[Intermediate] Multilingual Translation Reviewer','[Intermediate] FAQ Knowledge Base Bot','[Intermediate] Structured Invoice Extractor','[Intermediate] AI Quiz Generation Platform','[Intermediate] Conversation Memory Chat App','[Intermediate] Tool-Calling Weather Assistant','[Intermediate] AI Feedback Analysis Dashboard','[Intermediate] Vector Database Comparison Project','[Intermediate] LLM Output Validation Service','[Intermediate] AI Safety Filter Gateway','[Intermediate] Streaming Chat Interface','[Intermediate] RAG Evaluation Starter Suite','[Intermediate] Model Cost Tracking Dashboard','[Intermediate] Human Approval AI Workflow',
'[Advanced] Hybrid RAG Enterprise Search','[Advanced] Multi-Agent Research Platform','[Advanced] Multi-Tenant AI Assistant SaaS','[Advanced] LLM Gateway with Model Fallback','[Advanced] Secure Text-to-SQL Analytics Copilot','[Advanced] Contract Intelligence Platform','[Advanced] AI Incident Response Agent','[Advanced] Production Prompt Evaluation System','[Advanced] Multimodal Document Intelligence','[Advanced] Knowledge Graph RAG Platform','[Advanced] AI Recruitment Decision Support','[Advanced] Privacy-Preserving Healthcare Assistant','[Advanced] Agentic Customer Service Platform','[Advanced] Real-Time Voice AI Assistant','[Advanced] Enterprise Prompt Governance Hub','[Advanced] LLM Observability and Cost Platform','[Advanced] Fine-Tuning Data Preparation System','[Advanced] AI Red Team Evaluation Lab','[Advanced] Resilient Agent Workflow Engine','[Advanced] Personalized Learning AI Platform','[Advanced] AI Financial Document Analyst','[Advanced] Scalable Embedding Ingestion Service','[Advanced] Model Routing and Caching Platform','[Advanced] AI Compliance Audit Framework','[Advanced] Capstone Cloud-Native LLM Platform'
]::text[]) with ordinality t(title,n);

with candidates as (
 select c.id course_id,s.seq,s.title,s.focus,
   (select count(*) from public.course_projects cp where cp.course_id=c.id) existing_total
 from project_seed s join public.courses c on lower(btrim(c.title))=lower(s.course_title)
 where not exists(select 1 from public.course_projects e where e.course_id=c.id and lower(btrim(e.title))=lower(btrim(s.title)))
), ranked as (
 select *,row_number() over(partition by course_id order by seq) missing_rank from candidates
)
insert into public.course_projects(course_id,title,description)
select course_id,title,
 case when title like '[Intermediate]%' then
  'Build '||replace(title,'[Intermediate] ','')||' as a practical intermediate project focused on '||focus||'. Define requirements and users, implement a complete working workflow, validate inputs and outputs, handle errors and privacy responsibly, test with realistic scenarios, and submit the final artifact, evidence, setup instructions and a reflection explaining decisions and improvements.'
 else
  'Design and deliver '||replace(title,'[Advanced] ','')||' as an advanced, market-ready project focused on '||focus||'. Apply production architecture, security and privacy controls, integrations, automation, human approval where needed, observability, evaluation and failure recovery. Include realistic tests, measurable KPIs, technical documentation, risk analysis and a professional demonstration.' end
from ranked where existing_total + missing_rank <= 50;

end
$$;
commit;

select c.title course,count(cp.id) total_projects,
 count(cp.id) filter(where cp.title like '[Intermediate]%') intermediate,
 count(cp.id) filter(where cp.title like '[Advanced]%') advanced,
 count(cp.id) filter(where cp.title not like '[Intermediate]%' and cp.title not like '[Advanced]%') legacy
from public.courses c left join public.course_projects cp on cp.course_id=c.id
where lower(btrim(c.title)) in (
 lower('AI for Students & Freelancers'),lower('AI Productivity & Automation Mastery'),lower('Botpress Chatbot Development'),
 lower('Certified Research Methodology & Consultancy Training'),lower('Develop .NET applications'),lower('Develop LLM-Powered Applications')
)
group by c.id,c.title order by c.title;
