"use client";
import { useCallback, useEffect, useState } from "react";
import { createAdminAITool, deleteAITool, getAllAITools, reviewAITool, updateAIToolVideo } from "@/app/admin/ai-tools/actions";
import { PageHeader } from "@/components/page-header";
import { Icon } from "@/components/icon";
import { Toast, type ToastState } from "@/components/toast";
import { normalizeImageUrl } from "@/lib/image-url";
import type { AITool } from "@/lib/ai-tools";

const empty = { name: "", url: "", benefits: "", image_url: "", youtube_url: "" };
export function AIToolsManager() {
 const [rows,setRows]=useState<AITool[]>([]), [form,setForm]=useState(empty), [filter,setFilter]=useState("pending"), [saving,setSaving]=useState(false), [toast,setToast]=useState<ToastState>(null);
 const load=useCallback(async()=>{try{setRows(await getAllAITools() as AITool[]);}catch(e){setToast({type:"error",message:e instanceof Error?e.message:"Could not load AI tools."});}},[]); useEffect(()=>{void load();},[load]);
 async function add(e:React.FormEvent){e.preventDefault();setSaving(true);const r=await createAdminAITool(form);setSaving(false);if(!r.ok)return setToast({type:"error",message:r.error});setForm(empty);setToast({type:"success",message:"AI tool published."});await load();}
 async function review(id:string,status:"approved"|"rejected"){const note=window.prompt(status==="rejected"?"Reason for rejection (shown to student):":"Optional note for student:")??"";const r=await reviewAITool(id,status,note);if(!r.ok)return setToast({type:"error",message:r.error});setToast({type:"success",message:`Tool ${status}.`});await load();}
 async function remove(id:string){if(!window.confirm("Delete this AI tool permanently?"))return;const r=await deleteAITool(id);if(!r.ok)return setToast({type:"error",message:r.error});await load();}
 async function editVideo(row:AITool){const value=window.prompt("YouTube learning video URL (leave empty to remove):",row.youtube_url??"");if(value===null)return;const r=await updateAIToolVideo(row.id,value);if(!r.ok)return setToast({type:"error",message:r.error});setToast({type:"success",message:"Learning video updated."});await load();}
 const shown=filter==="all"?rows:rows.filter(r=>r.status===filter);
 return <div className="space-y-6"><Toast toast={toast} onClear={()=>setToast(null)}/><PageHeader eyebrow="Research directory" title="AI Tools" description="Review student suggestions or publish an admin-researched tool directly." />
 <form onSubmit={add} className="wc-card grid gap-4 p-5 md:grid-cols-2"><h2 className="text-xl font-black md:col-span-2">Add and publish tool</h2><input required className="wc-input" placeholder="Tool name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="url" className="wc-input" placeholder="Official URL" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><textarea required minLength={10} className="wc-input min-h-24 md:col-span-2" placeholder="Benefits for students" value={form.benefits} onChange={e=>setForm({...form,benefits:e.target.value})}/><input required type="url" className="wc-input md:col-span-2" placeholder="Public image or Google Drive URL" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/><input type="url" className="wc-input md:col-span-2" placeholder="YouTube learning video URL (optional)" value={form.youtube_url} onChange={e=>setForm({...form,youtube_url:e.target.value})}/><button disabled={saving} className="wc-primary-btn md:w-fit"><Icon name="publish"/>{saving?"Publishing...":"Publish tool"}</button></form>
 <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-black">Submissions ({shown.length})</h2><select className="wc-input w-auto" value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All</option></select></div><div className="grid gap-4">{shown.map(row=><article key={row.id} className="wc-card grid overflow-hidden md:grid-cols-[180px_1fr]"><div className="relative min-h-40 bg-surface-container"><img src={normalizeImageUrl(row.image_url)??row.image_url} alt="" className="absolute inset-0 h-full w-full object-cover"/></div><div className="p-5"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="text-xl font-black">{row.name}</h3><p className="text-xs text-on-surface-variant">Submitted by {row.submitter_email??"Admin"}</p></div><span className="text-xs font-black uppercase">{row.status}</span></div><p className="mt-3 whitespace-pre-line text-sm leading-6 text-on-surface-variant">{row.benefits}</p><a className="mt-2 inline-block text-sm font-bold text-secondary" href={row.url} target="_blank" rel="noreferrer">Open tool ↗</a><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>void editVideo(row)} className="wc-secondary-btn text-sm"><Icon name="play_circle"/>{row.youtube_url?"Edit video":"Add video"}</button>{row.status!=="approved"&&<button onClick={()=>void review(row.id,"approved")} className="wc-primary-btn text-sm"><Icon name="check"/>Approve</button>}{row.status!=="rejected"&&<button onClick={()=>void review(row.id,"rejected")} className="wc-secondary-btn text-sm"><Icon name="close"/>Reject</button>}<button onClick={()=>void remove(row.id)} className="wc-secondary-btn text-sm text-error"><Icon name="delete"/>Delete</button></div></div></article>)}{!shown.length&&<div className="wc-card p-10 text-center text-on-surface-variant">No {filter} submissions.</div>}</div></section></div>;
}



