"use client";

import Image from "next/image";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { PageHeader } from "@/components/page-header";
import { Icon } from "@/components/icon";
import { Toast, type ToastState } from "@/components/toast";
import { createSupabaseBrowserClient } from "@/lib/supabase/browser";
import type { SimpleCertificate, SoftwareHouse } from "@/lib/supabase/types";
import { deleteSimpleCertificate, saveSimpleCertificate, type SimpleCertificateInput } from "@/app/admin/actions";
import { toPng } from "html-to-image";
import { PDFDocument } from "pdf-lib";

const today = () => new Date().toISOString().slice(0, 10);
const plusWeeks = (date: string, weeks: number) => { const d = new Date(`${date}T12:00:00`); d.setDate(d.getDate() + weeks * 7); return d.toISOString().slice(0, 10); };
const blank = (): SimpleCertificateInput => ({ roll_number: "", student_name: "", course_name: "", duration_weeks: 8, start_date: today(), end_date: plusWeeks(today(), 8), software_house_id: null, software_house_name: "", logo_url: null, signatory_name: "", signatory_title: "", primary_color: "#1455d9", secondary_color: "#338ed8", text_color: "#244b5e", template_style: "modern", logo_size: 64, signature_url: null, digital_stamp_url: null, digital_stamp_size: 120, digital_stamp_opacity: 0.15, digital_stamp_offset_x: 40, hr_email: null, hr_contact_number: null, punctuality_percentage: 100, task_completion_percentage: 100, project_involvement_percentage: 100, software_house_name_position_x: 9, software_house_name_position_y: 9 });
const pretty = (date: string) => new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "long", year: "numeric" }).format(new Date(`${date}T12:00:00`));
const certificateInput = (row: SimpleCertificate): SimpleCertificateInput => ({ roll_number: row.roll_number, student_name: row.student_name, course_name: row.course_name, duration_weeks: row.duration_weeks, start_date: row.start_date, end_date: row.end_date, software_house_id: row.software_house_id, software_house_name: row.software_house_name, logo_url: row.logo_url, signatory_name: row.signatory_name, signatory_title: row.signatory_title, primary_color: row.primary_color || "#1455d9", secondary_color: row.secondary_color || "#338ed8", text_color: row.text_color || "#244b5e", template_style: row.template_style || "modern", logo_size: row.logo_size || 64, signature_url: row.signature_url || null, digital_stamp_url: row.digital_stamp_url || null, digital_stamp_size: row.digital_stamp_size || 120, digital_stamp_opacity: row.digital_stamp_opacity ?? 0.15, digital_stamp_offset_x: row.digital_stamp_offset_x ?? 40, hr_email: row.hr_email || null, hr_contact_number: row.hr_contact_number || null, punctuality_percentage: row.punctuality_percentage ?? 100, task_completion_percentage: row.task_completion_percentage ?? 100, project_involvement_percentage: row.project_involvement_percentage ?? 100, software_house_name_position_x: row.software_house_name_position_x ?? 9, software_house_name_position_y: row.software_house_name_position_y ?? 9 });

const certificateStyles = [
  ["modern", "Modern"], ["classic", "Classic"], ["executive", "Executive"],
  ["minimal", "Minimal"], ["geometric", "Geometric"], ["prestige", "Prestige"],
] as const;

export function SimpleCertificatesManager() {
  const supabase = useMemo(() => createSupabaseBrowserClient(), []);
  const [rows, setRows] = useState<SimpleCertificate[]>([]); const [houses, setHouses] = useState<SoftwareHouse[]>([]);
  const [form, setForm] = useState<SimpleCertificateInput>(blank()); const [editing, setEditing] = useState<string | undefined>();
  const [editorOpen, setEditorOpen] = useState(false);
  const [search, setSearch] = useState(""); const [houseFilter, setHouseFilter] = useState(""); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false);
  const [toast, setToast] = useState<ToastState>(null); const fileRef = useRef<HTMLInputElement>(null); const signatureFileRef = useRef<HTMLInputElement>(null); const certificateRef = useRef<HTMLDivElement>(null); const savedCertificateRef = useRef<HTMLDivElement>(null); const [exportingPng, setExportingPng] = useState(false); const [exportingPdf, setExportingPdf] = useState(false); const [exportingSavedId, setExportingSavedId] = useState<string | null>(null); const [savedExportData, setSavedExportData] = useState<SimpleCertificateInput>(blank()); const [uploadingSignature, setUploadingSignature] = useState(false);
  const formRef = useRef<HTMLFormElement>(null);
  const update = <K extends keyof SimpleCertificateInput>(key: K, value: SimpleCertificateInput[K]) => setForm((old) => ({ ...old, [key]: value }));
  const load = useCallback(async () => { setLoading(true); const [certs, companies] = await Promise.all([supabase.from("simple_certificates").select("*").order("created_at", { ascending: false }), supabase.from("software_houses").select("*").eq("is_active", true).order("display_order")]); if (certs.error) setToast({ type: "error", message: certs.error.message }); setRows((certs.data as SimpleCertificate[]) ?? []); setHouses((companies.data as SoftwareHouse[]) ?? []); setLoading(false); }, [supabase]);
  useEffect(() => { void load(); }, [load]);
  const filtered = rows.filter((r) => (!search || `${r.roll_number} ${r.student_name}`.toLowerCase().includes(search.toLowerCase())) && (!houseFilter || r.software_house_name === houseFilter));
  const chooseHouse = (id: string) => { const h = houses.find((x) => x.id === id); setForm((f) => ({ ...f, software_house_id: h?.id ?? null, software_house_name: h?.name ?? "", logo_url: h?.logo_url ?? null, signatory_name: h?.ceo_name ?? h?.hr_manager_name ?? "", signature_url: h?.head_signature_url ?? null, digital_stamp_url: h?.digital_stamp_url ?? null, digital_stamp_size: h?.digital_stamp_size ?? 80, hr_email: h?.hr_email ?? null, hr_contact_number: h?.hr_contact_number ?? null })); };
  async function uploadLogo(file: File) { if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) { setToast({ type: "error", message: "PNG, JPG, WebP or SVG logo up to 5 MB is allowed." }); return; } setUploading(true); const ext = file.name.split(".").pop()?.toLowerCase() || "png"; const path = `${Date.now()}-${crypto.randomUUID()}.${ext}`; const result = await supabase.storage.from("certificate-logos").upload(path, file, { upsert: false }); if (result.error) setToast({ type: "error", message: result.error.message }); else { const { data } = supabase.storage.from("certificate-logos").getPublicUrl(path); update("logo_url", data.publicUrl); setToast({ type: "success", message: "Logo uploaded to Supabase." }); } setUploading(false); }
  async function uploadSignature(file: File) { if (!file.type.startsWith("image/") || file.size > 5 * 1024 * 1024) { setToast({ type: "error", message: "Please upload a PNG/JPG signature up to 5 MB." }); return; } setUploadingSignature(true); const ext = file.name.split(".").pop()?.toLowerCase() || "png"; const path = `signatures/${Date.now()}-${crypto.randomUUID()}.${ext}`; const result = await supabase.storage.from("certificate-logos").upload(path, file); if (result.error) setToast({ type: "error", message: result.error.message }); else { const { data } = supabase.storage.from("certificate-logos").getPublicUrl(path); update("signature_url", data.publicUrl); setToast({ type: "success", message: "Digital signature uploaded." }); } setUploadingSignature(false); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); const wasEditing = Boolean(editing); const result = await saveSimpleCertificate(form, editing); setBusy(false); if (!result.success) return setToast({ type: "error", message: result.error ?? "Save failed." }); setToast({ type: "success", message: wasEditing ? "Certificate updated with the selected style." : "Certificate saved with the selected style." }); setEditing(result.data?.id); setEditorOpen(false); await load(); }
  function edit(row: SimpleCertificate) { setEditing(row.id); setForm(certificateInput(row)); setEditorOpen(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function newCertificate() { setEditing(undefined); setForm(blank()); setEditorOpen(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(id: string) { if (!confirm("Delete this certificate record?")) return; const result = await deleteSimpleCertificate(id); if (!result.success) setToast({ type: "error", message: result.error ?? "Delete failed." }); else { setRows((old) => old.filter((r) => r.id !== id)); setToast({ type: "success", message: "Certificate deleted." }); } }
  function print() { window.print(); }
  const exportFileName = () => { const name = (form.student_name || "certificate").trim().replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase(); return `${name || "certificate"}-${form.roll_number || "preview"}`; };
  async function renderCertificatePng() { if (!certificateRef.current) throw new Error("Certificate preview is unavailable."); const exportWidth = 1120; const exportHeight = 792; return toPng(certificateRef.current, { cacheBust: true, backgroundColor: "#ffffff", width: exportWidth, height: exportHeight, canvasWidth: exportWidth * 2, canvasHeight: exportHeight * 2, pixelRatio: 1, style: { width: `${exportWidth}px`, height: `${exportHeight}px`, maxWidth: "none", margin: "0", boxShadow: "none", aspectRatio: "auto" } }); }
  async function downloadPng() { setExportingPng(true); try { const dataUrl = await renderCertificatePng(); const link = document.createElement("a"); link.download = `${exportFileName()}.png`; link.href = dataUrl; link.click(); setToast({ type: "success", message: "High-resolution certificate PNG downloaded." }); } catch { setToast({ type: "error", message: "PNG could not be generated. Please verify that the logo is publicly accessible." }); } finally { setExportingPng(false); } }
  async function downloadColorPdf() { setExportingPdf(true); try { const dataUrl = await renderCertificatePng(); const pngBytes = await fetch(dataUrl).then((response) => response.arrayBuffer()); const pdf = await PDFDocument.create(); const page = pdf.addPage([841.89, 595.28]); const image = await pdf.embedPng(pngBytes); page.drawImage(image, { x: 0, y: 0, width: page.getWidth(), height: page.getHeight() }); const bytes = await pdf.save(); const blob = new Blob([new Uint8Array(bytes)], { type: "application/pdf" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.download = `${exportFileName()}.pdf`; link.href = url; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setToast({ type: "success", message: "Full-color A4 PDF downloaded." }); } catch { setToast({ type: "error", message: "Color PDF could not be generated. Please verify that the logo is publicly accessible." }); } finally { setExportingPdf(false); } }
  async function downloadSavedPdf(row: SimpleCertificate) { setExportingSavedId(row.id); setSavedExportData(certificateInput(row)); try { await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))); if (!savedCertificateRef.current) throw new Error("Saved certificate preview is unavailable."); const dataUrl = await toPng(savedCertificateRef.current, { cacheBust: true, backgroundColor: "#ffffff", width: 1120, height: 792, canvasWidth: 2240, canvasHeight: 1584, pixelRatio: 1, style: { width: "1120px", height: "792px", maxWidth: "none", margin: "0", boxShadow: "none", aspectRatio: "auto" } }); const pngBytes = await fetch(dataUrl).then((response) => response.arrayBuffer()); const pdf = await PDFDocument.create(); const page = pdf.addPage([841.89, 595.28]); const image = await pdf.embedPng(pngBytes); page.drawImage(image, { x: 0, y: 0, width: page.getWidth(), height: page.getHeight() }); const bytes = await pdf.save(); const blob = new Blob([new Uint8Array(bytes)], { type: "application/pdf" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); const name = (row.student_name || "certificate").trim().replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase(); link.download = `${name || "certificate"}-${row.roll_number || "record"}.pdf`; link.href = url; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setToast({ type: "success", message: `${row.student_name}'s certificate PDF downloaded.` }); } catch { setToast({ type: "error", message: "Certificate PDF could not be generated. Please verify that its logo is publicly accessible." }); } finally { setExportingSavedId(null); } }
  return <><Toast toast={toast} onClear={() => setToast(null)} /><PageHeader eyebrow="Certificates & Letters" title="Simple Certificates" description="Create, print and retain searchable student certificate records." />
    <div className="mb-4 flex flex-wrap items-center justify-end gap-2 print:hidden">
      <button type="button" onClick={newCertificate} className="wc-primary-btn px-4 py-2"><Icon name="add" />New Certificate</button>
      <button type="button" onClick={() => setEditorOpen((open) => !open)} className="wc-secondary-btn px-4 py-2"><Icon name={editorOpen ? "visibility" : "tune"} />{editorOpen ? "Full Preview" : "Edit Settings"}</button>
      <button type="button" onClick={() => formRef.current?.requestSubmit()} disabled={busy} className="wc-primary-btn px-4 py-2"><Icon name="save" />{busy ? "Saving…" : editing ? "Update Certificate" : "Save Certificate"}</button>
    </div>
    <div className="print:block">
      <form ref={formRef} onSubmit={submit} className={`wc-card fixed bottom-4 right-4 top-24 z-40 w-[min(420px,calc(100vw-2rem))] space-y-4 overflow-y-auto p-5 shadow-2xl transition duration-300 print:hidden ${editorOpen ? "translate-x-0 opacity-100" : "pointer-events-none translate-x-[calc(100%+2rem)] opacity-0"}`}>
        <div className="sticky -top-5 z-30 -mx-5 -mt-5 flex items-center justify-between border-b border-outline-variant bg-surface px-5 py-4"><div><h2 className="font-bold text-on-surface">{editing ? "Edit certificate" : "New certificate"}</h2><p className="text-xs text-on-surface-variant">Changes appear live on the certificate.</p></div><button type="button" className="rounded-full p-2 hover:bg-surface-container" onClick={() => setEditorOpen(false)} title="Close settings and preview"><Icon name="close" /></button></div>
        <div className="rounded-xl border border-outline-variant bg-surface-container/40 p-3"><span className="wc-label mb-2 block">Select certificate style</span><div className="flex snap-x gap-2 overflow-x-auto pb-2">{certificateStyles.map(([value, label]) => <button key={value} type="button" onClick={() => update("template_style", value)} className={`w-[104px] shrink-0 snap-start rounded-xl border-2 p-2 text-xs font-bold transition ${form.template_style === value ? "border-primary bg-primary/10 text-primary" : "border-outline-variant bg-surface hover:border-primary/50"}`}><StyleThumbnail styleName={value} /><Icon name={form.template_style === value ? "check_circle" : "image"} className="mr-1 text-sm" />{label}</button>)}</div><p className="mt-1 text-center text-[11px] text-on-surface-variant">Scroll, click a style to preview it, then save to finalize.</p></div>
        <Field label="Roll number *"><input required className="wc-input" value={form.roll_number} onChange={(e) => update("roll_number", e.target.value)} placeholder="e.g. WC-2026-001" /></Field>
        <Field label="Student name *"><input required className="wc-input" value={form.student_name} onChange={(e) => update("student_name", e.target.value)} /></Field>
        <Field label="Internship name *"><input required className="wc-input" value={form.course_name} onChange={(e) => update("course_name", e.target.value)} placeholder="Web Development" /></Field>
        <div className="grid grid-cols-2 gap-3"><Field label="Duration (weeks)"><input min={1} type="number" className="wc-input" value={form.duration_weeks} onChange={(e) => { const weeks = Number(e.target.value); setForm((f) => ({ ...f, duration_weeks: weeks, end_date: plusWeeks(f.start_date, weeks) })); }} /></Field><Field label="Start date *"><input required type="date" className="wc-input" value={form.start_date} onChange={(e) => { const start = e.target.value; setForm((f) => ({ ...f, start_date: start, end_date: plusWeeks(start, f.duration_weeks) })); }} /></Field></div>
        <Field label="End date *"><input required type="date" className="wc-input" value={form.end_date} onChange={(e) => update("end_date", e.target.value)} /></Field>
        <Field label="Software house"><select className="wc-input" value={form.software_house_id ?? ""} onChange={(e) => chooseHouse(e.target.value)}><option value="">Custom software house</option>{houses.map((h) => <option key={h.id} value={h.id}>{h.name}</option>)}</select></Field>
        <Field label="Software house name *"><input required className="wc-input" value={form.software_house_name} onChange={(e) => update("software_house_name", e.target.value)} /></Field>
        <div className="rounded-xl border border-outline-variant bg-surface-container/40 p-3"><div className="mb-3 flex items-center justify-between"><span className="wc-label">Software house name position</span><button type="button" className="text-xs font-semibold text-primary" onClick={() => setForm((old) => ({ ...old, software_house_name_position_x: 9, software_house_name_position_y: 9 }))}>Reset</button></div><Field label={`Horizontal — ${form.software_house_name_position_x}% from left`}><div className="flex items-center gap-2"><span className="text-xs">Left</span><input aria-label="Software house name horizontal position" type="range" min={2} max={80} value={form.software_house_name_position_x} onChange={(e) => update("software_house_name_position_x", Number(e.target.value))} className="w-full accent-primary" /><span className="text-xs">Right</span></div></Field><div className="mt-3"><Field label={`Vertical — ${form.software_house_name_position_y}% from top`}><div className="flex items-center gap-2"><span className="text-xs">Up</span><input aria-label="Software house name vertical position" type="range" min={2} max={80} value={form.software_house_name_position_y} onChange={(e) => update("software_house_name_position_y", Number(e.target.value))} className="w-full accent-primary" /><span className="text-xs">Down</span></div></Field></div><p className="mt-2 text-[10px] text-on-surface-variant">Move both sliders while watching the live certificate preview.</p></div>
        <div><span className="wc-label mb-2 block">Performance on certificate</span><div className="grid grid-cols-3 gap-2"><PercentageField label="Punctuality" value={form.punctuality_percentage} onChange={(value) => update("punctuality_percentage", value)} /><PercentageField label="Task completion" value={form.task_completion_percentage} onChange={(value) => update("task_completion_percentage", value)} /><PercentageField label="Project involvement" value={form.project_involvement_percentage} onChange={(value) => update("project_involvement_percentage", value)} /></div></div>
        <Field label="Company logo"><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e) => e.target.files?.[0] && void uploadLogo(e.target.files[0])} /><button type="button" className="wc-secondary-btn w-full justify-center py-2" disabled={uploading} onClick={() => fileRef.current?.click()}><Icon name="cloud_upload" />{uploading ? "Uploading…" : "Upload to Supabase"}</button></Field>
        {form.logo_url && <Field label={`Logo size — ${form.logo_size}px`}><div className="flex items-center gap-3"><Icon name="remove" className="text-sm" /><input type="range" min={32} max={180} step={4} value={form.logo_size} onChange={(e) => update("logo_size", Number(e.target.value))} className="w-full accent-primary" /><Icon name="add" className="text-sm" /></div></Field>}
        <div><span className="wc-label mb-2 block">Certificate color scheme</span><div className="grid grid-cols-3 gap-3"><ColorField label="Primary" value={form.primary_color} onChange={(value) => update("primary_color", value)} /><ColorField label="Accent" value={form.secondary_color} onChange={(value) => update("secondary_color", value)} /><ColorField label="Text" value={form.text_color} onChange={(value) => update("text_color", value)} /></div></div>
        <div className="grid grid-cols-2 gap-3"><Field label="HR email (optional)"><input type="email" className="wc-input" value={form.hr_email ?? ""} onChange={(e) => update("hr_email", e.target.value || null)} placeholder="Leave blank to hide" /></Field><Field label="HR contact (optional)"><input type="tel" className="wc-input" value={form.hr_contact_number ?? ""} onChange={(e) => update("hr_contact_number", e.target.value || null)} placeholder="Leave blank to hide" /></Field></div>
        <Field label="Digital signature"><input ref={signatureFileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => e.target.files?.[0] && void uploadSignature(e.target.files[0])} /><button type="button" className="wc-secondary-btn w-full justify-center py-2" disabled={uploadingSignature} onClick={() => signatureFileRef.current?.click()}><Icon name="draw" />{uploadingSignature ? "Uploading…" : form.signature_url ? "Change signature" : "Upload signature"}</button></Field>
        {form.digital_stamp_url && <div className="grid grid-cols-2 gap-3"><Field label={`Stamp size — ${form.digital_stamp_size}px`}><input aria-label="Stamp size" type="range" min={32} max={180} step={4} value={form.digital_stamp_size} onChange={(e) => update("digital_stamp_size", Number(e.target.value))} className="w-full accent-primary" /></Field><Field label={`Stamp opacity — ${Math.round(form.digital_stamp_opacity * 100)}%`}><input aria-label="Stamp opacity" type="range" min={0} max={100} step={1} value={Math.round(form.digital_stamp_opacity * 100)} onChange={(e) => update("digital_stamp_opacity", Number(e.target.value) / 100)} className="w-full accent-primary" /></Field><div className="col-span-2"><Field label={`Stamp position — ${form.digital_stamp_offset_x === 0 ? "Center" : form.digital_stamp_offset_x > 0 ? `${form.digital_stamp_offset_x}px right` : `${Math.abs(form.digital_stamp_offset_x)}px left`}`}><div className="flex items-center gap-3"><span className="text-xs text-on-surface-variant">Left</span><input aria-label="Stamp horizontal position" type="range" min={-240} max={240} step={4} value={form.digital_stamp_offset_x} onChange={(e) => update("digital_stamp_offset_x", Number(e.target.value))} className="w-full accent-primary" /><span className="text-xs text-on-surface-variant">Right</span><button type="button" className="rounded-lg border border-outline-variant px-2 py-1 text-xs" onClick={() => update("digital_stamp_offset_x", 0)}>Center</button></div></Field></div></div>}
        <button disabled={busy} className="wc-primary-btn w-full justify-center py-3"><Icon name="save" />{busy ? "Saving…" : editing ? "Update certificate" : "Save certificate"}</button>
      </form>
      <div><div className="mb-3 flex flex-wrap justify-end gap-2 print:hidden"><button onClick={() => void downloadPng()} disabled={exportingPng || exportingPdf} className="wc-secondary-btn px-4 py-2"><Icon name="download" />{exportingPng ? "Creating PNG…" : "Download PNG"}</button><button onClick={() => void downloadColorPdf()} disabled={exportingPdf || exportingPng} className="wc-primary-btn px-4 py-2"><Icon name="picture_as_pdf" />{exportingPdf ? "Creating PDF…" : "Download Color PDF"}</button><button onClick={print} className="wc-secondary-btn px-4 py-2"><Icon name="print" />Quick Print</button></div>
        <CertificatePreview data={form} certificateRef={certificateRef} />
      </div>
    </div>
    <section className="wc-card mt-7 overflow-hidden print:hidden"><div className="border-b border-outline-variant p-5"><h2 className="font-bold">Saved certificate records</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="wc-input" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search roll number or student name…" /><select className="wc-input" value={houseFilter} onChange={(e) => setHouseFilter(e.target.value)}><option value="">All software houses</option>{[...new Set(rows.map((r) => r.software_house_name))].map((name) => <option key={name}>{name}</option>)}</select></div></div>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-container text-xs uppercase text-on-surface-variant"><tr><th className="p-4">Roll #</th><th className="p-4">Student</th><th className="p-4">Course</th><th className="p-4">Software house</th><th className="p-4">Dates</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-8 text-center">Loading…</td></tr> : filtered.length === 0 ? <tr><td colSpan={6} className="p-8 text-center text-on-surface-variant">No certificates found.</td></tr> : filtered.map((r) => <tr key={r.id} className="border-t border-outline-variant"><td className="p-4 font-bold">{r.roll_number}</td><td className="p-4">{r.student_name}</td><td className="p-4">{r.course_name}</td><td className="p-4">{r.software_house_name}</td><td className="p-4 text-xs">{r.start_date} — {r.end_date}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => void downloadSavedPdf(r)} disabled={exportingSavedId !== null} className="rounded-lg p-2 text-primary hover:bg-primary/10 disabled:opacity-50" title="Download this student's PDF"><Icon name={exportingSavedId === r.id ? "hourglass_top" : "picture_as_pdf"} /></button><button onClick={() => edit(r)} className="rounded-lg p-2 hover:bg-surface-container" title="Edit"><Icon name="edit" /></button><button onClick={() => void remove(r.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50" title="Delete"><Icon name="delete" /></button></div></td></tr>)}</tbody></table></div>
    </section><div className="pointer-events-none fixed -left-[100000px] top-0 h-[792px] w-[1120px] overflow-hidden" aria-hidden="true"><CertificatePreview data={savedExportData} certificateRef={savedCertificateRef} /></div></>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="wc-label mb-1.5 block">{label}</span>{children}</label>; }

function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-center text-[11px] text-on-surface-variant"><input type="color" value={value} onChange={(e) => onChange(e.target.value)} className="mb-1 h-10 w-full cursor-pointer rounded-lg border border-outline-variant bg-transparent p-1" /><span>{label}</span></label>; }

function PercentageField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-center text-[10px] text-on-surface-variant"><span className="mb-1 block h-7 leading-3">{label}</span><div className="relative"><input required type="number" min={0} max={100} value={value} onChange={(e) => onChange(Math.min(100, Math.max(0, Number(e.target.value))))} className="wc-input py-2 pr-6 text-center text-sm" /><span className="absolute right-2 top-1/2 -translate-y-1/2">%</span></div></label>; }

function StyleThumbnail({ styleName }: { styleName: SimpleCertificateInput["template_style"] }) { return <span className="relative mb-2 block h-12 overflow-hidden bg-white shadow-sm">
  {styleName === "modern" && <><i className="absolute left-0 top-0 h-5 w-5 bg-blue-600" /><i className="absolute bottom-1 right-1 h-8 w-12 border border-blue-600" /></>}
  {styleName === "classic" && <i className="absolute inset-1 border-4 border-double border-slate-600" />}
  {styleName === "executive" && <i className="absolute -left-2 -top-5 h-9 w-[120%] rounded-b-[50%] bg-blue-700" />}
  {styleName === "minimal" && <><i className="absolute inset-x-2 top-2 border-t-2 border-amber-500" /><i className="absolute inset-x-5 bottom-2 border-t border-slate-500" /></>}
  {styleName === "geometric" && <><i className="absolute -left-3 -top-3 h-8 w-8 rotate-45 bg-cyan-500" /><i className="absolute -bottom-3 -right-3 h-9 w-9 rotate-45 bg-blue-700" /></>}
  {styleName === "prestige" && <><i className="absolute inset-1 border-2 border-amber-500" /><i className="absolute left-1/2 top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rotate-45 border border-amber-500" /></>}
</span>; }

const CertificatePreview = ({ data, certificateRef }: { data: SimpleCertificateInput; certificateRef: React.RefObject<HTMLDivElement | null> }) => <div ref={certificateRef} className="certificate-print relative mx-auto aspect-[1.414/1] w-full max-w-[1100px] overflow-hidden bg-white p-[6%] shadow-xl print:max-w-none print:shadow-none" style={{ color: data.text_color }}>
  {data.template_style === "modern" && <><div className="absolute left-0 top-0 h-24 w-24" style={{ backgroundColor: data.primary_color }} /><div className="absolute left-12 top-0 h-16 w-16 opacity-90" style={{ backgroundColor: data.secondary_color }} /><div className="absolute bottom-0 right-0 h-20 w-20" style={{ backgroundColor: data.primary_color }} /><div className="absolute bottom-10 right-0 h-16 w-16 opacity-90" style={{ backgroundColor: data.secondary_color }} /><div className="absolute inset-[7%] border-2" style={{ borderColor: data.primary_color }} /></>}
  {data.template_style === "classic" && <><div className="absolute inset-3 border-[14px]" style={{ borderColor: data.primary_color }} /><div className="absolute inset-9 border-4 border-double opacity-60" style={{ borderColor: data.text_color }} /><div className="absolute inset-12 border border-dashed opacity-40" style={{ borderColor: data.text_color }} /><span className="absolute left-12 top-10 text-3xl opacity-50">★</span><span className="absolute right-12 top-10 text-3xl opacity-50">★</span><span className="absolute bottom-10 left-12 text-3xl opacity-50">★</span><span className="absolute bottom-10 right-12 text-3xl opacity-50">★</span></>}
  {data.template_style === "executive" && <><div className="absolute -left-[8%] -top-[29%] h-[42%] w-[116%] rounded-[0_0_50%_50%]" style={{ backgroundColor: data.primary_color }} /><div className="absolute -left-[8%] -top-[26%] h-[42%] w-[116%] rounded-[0_0_50%_50%] opacity-55" style={{ backgroundColor: data.secondary_color }} /><div className="absolute inset-x-[5%] bottom-[5%] top-[6%] border-x-2 border-b-2" style={{ borderColor: data.primary_color }} /><div className="absolute right-[9%] top-[14%] flex h-16 w-16 items-center justify-center rounded-full border-4 text-2xl font-black" style={{ borderColor: data.secondary_color, color: data.secondary_color }}>★</div></>}
  {data.template_style === "minimal" && <><div className="absolute inset-[5%] border" style={{ borderColor: data.secondary_color }} /><div className="absolute inset-x-[14%] top-[8%] border-t-4" style={{ borderColor: data.primary_color }} /><div className="absolute inset-x-[14%] bottom-[8%] border-t" style={{ borderColor: data.primary_color }} /></>}
  {data.template_style === "geometric" && <><div className="absolute -left-20 -top-20 h-52 w-52 rotate-45" style={{ backgroundColor: data.primary_color }} /><div className="absolute -left-12 top-20 h-24 w-24 rotate-45 opacity-70" style={{ backgroundColor: data.secondary_color }} /><div className="absolute -bottom-20 -right-20 h-52 w-52 rotate-45" style={{ backgroundColor: data.primary_color }} /></>}
  {data.template_style === "prestige" && <><div className="absolute inset-4 border-[6px] border-double" style={{ borderColor: data.primary_color }} /><div className="absolute inset-10 border" style={{ borderColor: data.secondary_color }} /></>}
  <div className={`absolute z-20 max-w-[32%] break-words text-xs font-bold uppercase tracking-[.12em] sm:text-sm ${data.template_style === "executive" || data.template_style === "geometric" ? "text-white" : ""}`} style={{ left: `${data.software_house_name_position_x}%`, top: `${data.software_house_name_position_y}%` }}>{data.software_house_name || "Software House"}</div>
  {data.digital_stamp_url && <div className="pointer-events-none absolute bottom-[13%] left-1/2 z-0 -translate-x-1/2" style={{ height: data.digital_stamp_size, width: data.digital_stamp_size, opacity: data.digital_stamp_opacity, marginLeft: data.digital_stamp_offset_x }}><Image src={data.digital_stamp_url} alt="Software house stamp" fill className="object-contain" unoptimized /></div>}
  <div className={`relative z-10 flex h-full flex-col items-center justify-center text-center ${data.template_style === "executive" ? "pt-[7%]" : ""}`}>
    {data.logo_url ? <div className="relative mb-3 shrink-0" style={{ height: data.logo_size, width: data.logo_size * 1.75 }}><Image src={data.logo_url} alt="Software house logo" fill className="object-contain" unoptimized /></div> : <div className="mb-3 text-sm font-bold uppercase tracking-[.2em]">{data.software_house_name || "Software House"}</div>}
    <h1 className={`text-3xl sm:text-5xl ${data.template_style === "classic" ? "font-serif font-black uppercase tracking-[.14em]" : data.template_style === "executive" ? "font-black uppercase tracking-wide" : "font-light"}`}>{data.template_style === "classic" ? "Certificate" : "Certificate of Completion"}</h1>{data.template_style === "classic" && <p className="mt-1 font-serif text-sm font-bold uppercase tracking-[.3em]">of Completion</p>}<p className="mt-5 text-sm sm:text-lg">This certificate is proudly awarded to</p>
    <h2 className={`my-3 text-3xl sm:text-6xl ${data.template_style === "classic" || data.template_style === "prestige" ? "font-serif italic" : "font-black"}`} style={{ color: data.text_color }}>{data.student_name || "Student Name"}</h2>
    <p className="max-w-3xl text-sm leading-7 sm:text-xl">for successfully completing the <b>{data.course_name || "Internship Name"} Internship</b> at <b>{data.software_house_name || "Software House"}</b> over a period of <b>{data.duration_weeks || 8} weeks</b>, from {pretty(data.start_date)} to {pretty(data.end_date)}.</p>
    <p className="mt-3 text-xs tracking-wide sm:text-base">Software House Registration No. <b>{data.roll_number || "REGISTRATION-NUMBER"}</b></p>
    <div className="mt-4 grid w-[72%] grid-cols-3 gap-3"><Metric label="Punctuality" value={data.punctuality_percentage} color={data.primary_color} /><Metric label="Task Completion" value={data.task_completion_percentage} color={data.primary_color} /><Metric label="Project Involvement" value={data.project_involvement_percentage} color={data.primary_color} /></div>
    <div className="relative mx-auto mt-4 w-[58%] min-w-72 max-w-2xl text-center">
      <div>
        {data.signature_url && <div className="relative mx-auto h-12 w-36 translate-y-2"><Image src={data.signature_url} alt="Digital signature" fill className="object-contain" unoptimized /></div>}
        <div className="border-b-2 pb-2" style={{ borderColor: data.primary_color }}>&nbsp;</div>
        <p className="mt-2 break-words text-xs font-semibold leading-4">Head of {data.software_house_name || "Software House"}</p>
        {(data.hr_email || data.hr_contact_number) && <p className="mt-1 break-words text-[10px] leading-4 text-slate-600">{data.hr_email && <span>HR: {data.hr_email}</span>}{data.hr_email && data.hr_contact_number && <span> · </span>}{data.hr_contact_number && <span>{data.hr_contact_number}</span>}</p>}
      </div>
    </div>
  </div><style jsx global>{`@media print { body * { visibility:hidden!important } .certificate-print,.certificate-print * { visibility:visible!important } .certificate-print { position:fixed!important; inset:0!important; width:100vw!important; height:100vh!important; aspect-ratio:auto!important; } @page { size:A4 landscape; margin:0 } }`}</style>
</div>;

function Metric({ label, value, color }: { label: string; value: number; color: string }) { return <div className="rounded-md border bg-white/80 px-2 py-1.5" style={{ borderColor: color }}><b className="block text-sm sm:text-lg" style={{ color }}>{value}%</b><span className="block text-[9px] font-bold uppercase tracking-wide sm:text-[11px]">{label}</span></div>; }
