"use server";
import { revalidatePath } from "next/cache";
import { requireAdminOnly } from "@/lib/admin-access";
import { createSupabaseServiceClient } from "@/lib/supabase/service";
import { validateAITool } from "@/lib/ai-tools";

type ToolInput = { name: string; url: string; benefits: string; image_url: string; youtube_url?: string };
export async function getAllAITools() { await requireAdminOnly(); const supabase = createSupabaseServiceClient(); const [{ data, error }, { data: admins, error: adminError }] = await Promise.all([supabase.from("ai_tools").select("*").order("created_at", { ascending: false }), supabase.from("profiles").select("id").eq("role", "admin")]); if (error) throw new Error(error.message); if (adminError) throw new Error(adminError.message); const adminIds = new Set((admins ?? []).map((row) => row.id)); return (data ?? []).map((row) => ({ ...row, submitter_role: row.submitted_by && adminIds.has(row.submitted_by) ? "admin" as const : "student" as const })); }
export async function createAdminAITool(input: ToolInput) { const admin = await requireAdminOnly(); const validation = validateAITool(input); if (!validation.ok) return validation; const now = new Date().toISOString(); const { error } = await createSupabaseServiceClient().from("ai_tools").insert({ ...validation.data, submitted_by: admin.id, submitter_email: admin.email ?? null, status: "approved", reviewed_by: admin.id, reviewed_at: now, published_at: now }); if (error) return { ok: false, error: error.code === "23505" ? "This AI tool URL already exists." : error.message }; refresh(); return { ok: true }; }
export async function updateAIToolVideo(id: string, youtubeUrl: string) { await requireAdminOnly(); const value = youtubeUrl.trim(); if (value) { try { const url = new URL(value); if (!/^(www\.)?(youtube\.com|youtu\.be)$/i.test(url.hostname)) throw new Error(); } catch { return { ok: false, error: "Enter a valid YouTube video URL." }; } } const { error } = await createSupabaseServiceClient().from("ai_tools").update({ youtube_url: value || null, updated_at: new Date().toISOString() }).eq("id", id); if (error) return { ok: false, error: error.message }; refresh(); return { ok: true }; }
export async function reviewAITool(id: string, status: "approved" | "rejected", admin_note: string) { const admin = await requireAdminOnly(); const now = new Date().toISOString(); const { error } = await createSupabaseServiceClient().from("ai_tools").update({ status, admin_note: admin_note.trim() || null, reviewed_by: admin.id, reviewed_at: now, published_at: status === "approved" ? now : null, updated_at: now }).eq("id", id); if (error) return { ok: false, error: error.message }; refresh(); return { ok: true }; }
export async function deleteAITool(id: string) { await requireAdminOnly(); const { error } = await createSupabaseServiceClient().from("ai_tools").delete().eq("id", id); if (error) return { ok: false, error: error.message }; refresh(); return { ok: true }; }
function refresh() { revalidatePath("/ai-tools"); revalidatePath("/student/ai-tools"); revalidatePath("/admin/ai-tools"); }
