-- Complete 30-day practical curriculum for AI Productivity & Automation Mastery.
-- Tools are free, open-source, self-hostable, or have a usable free tier as of August 2026.

begin;

with selected_course as (
  select id
  from public.courses
  where lower(btrim(title)) = lower('AI Productivity & Automation Mastery')
  order by created_at asc
  limit 1
), rows (day_number, title, english_video, urdu_video, practice_project) as (
  values
    (1, 'AI Productivity Foundations: Responsible Use, Privacy and Prompting', 'Official guide: https://ai.google.dev/gemini-api/docs/prompting-strategies', 'YouTube search: AI prompting complete course Urdu Hindi', 'Project: Build a reusable prompt library with 20 prompts for email, planning, research, sales and customer support; document privacy rules and a human-review checklist.'),
    (2, 'ChatGPT Free: Writing, Analysis, Files and Custom Workflows', 'Official guide: https://help.openai.com/en/collections/3742473-chatgpt', 'YouTube search: ChatGPT productivity automation Urdu Hindi', 'Project: Create an AI office assistant workflow that turns rough notes into a polished email, meeting agenda, action list and weekly report.'),
    (3, 'Google Gemini Free: Workspace Productivity and Multimodal Tasks', 'Official guide: https://support.google.com/gemini/', 'YouTube search: Google Gemini complete course Urdu Hindi', 'Project: Build a business launch pack from one brief: market questions, product copy, spreadsheet structure, social captions and image-analysis notes.'),
    (4, 'Claude Free and Microsoft Copilot: Long Documents and Office Tasks', 'Official guides: https://support.anthropic.com/ and https://support.microsoft.com/copilot', 'YouTube search: Claude AI Microsoft Copilot tutorial Urdu Hindi', 'Project: Compare two AI assistants by summarizing a long policy document, extracting risks and producing an executive memo with verified facts.'),
    (5, 'Perplexity Free: Cited Web Research and Fact Verification', 'Official guide: https://www.perplexity.ai/help-center', 'YouTube search: Perplexity AI research tutorial Urdu Hindi', 'Project: Produce a cited competitor-research report for a Pakistani small business, verify five claims manually and include a source-quality scorecard.'),
    (6, 'NotebookLM Free: Source-Grounded Knowledge and Study Systems', 'Official guide: https://support.google.com/notebooklm/', 'YouTube search: NotebookLM complete tutorial Urdu Hindi', 'Project: Upload course PDFs and create a grounded FAQ, study guide, quiz, briefing document and audio-overview plan with source citations.'),
    (7, 'Google AI Studio and Free Model Prototyping', 'Official guide: https://ai.google.dev/gemini-api/docs/ai-studio-quickstart', 'YouTube search: Google AI Studio Gemini API free Urdu Hindi', 'Project: Prototype a structured lead-qualification assistant that returns validated JSON and test it against 20 sample customer inquiries.'),
    (8, 'Hugging Face Spaces and Open Models', 'Official guide: https://huggingface.co/docs/hub/spaces-overview', 'YouTube search: Hugging Face Spaces open source AI Urdu Hindi', 'Project: Evaluate five free Spaces or open models for summarization, translation, image processing and speech; publish a comparison matrix.'),
    (9, 'Ollama: Private Local AI Without Per-Request Cost', 'Official guide: https://docs.ollama.com/quickstart', 'YouTube search: Ollama local AI setup Urdu Hindi', 'Project: Install a suitable local model, create a private document summarizer and measure speed, memory use and answer quality on three documents.'),
    (10, 'Canva Magic Studio and Adobe Express Free: Branded Content', 'Official guides: https://www.canva.com/help/magic-studio/ and https://helpx.adobe.com/express/', 'YouTube search: Canva AI Adobe Express free tutorial Urdu Hindi', 'Project: Design a consistent mini brand kit plus five social posts, one flyer and one presentation cover for a local service business.'),
    (11, 'Ideogram and Microsoft Designer: AI Image Workflows', 'Official guides: https://docs.ideogram.ai/ and https://support.microsoft.com/designer', 'YouTube search: Ideogram Microsoft Designer AI Urdu Hindi', 'Project: Create a ten-image campaign with readable text, consistent colors and three aspect ratios; record prompts, seeds/settings and selection reasons.'),
    (12, 'Gamma and Napkin AI: Presentations and Visual Explanations', 'Official guides: https://help.gamma.app/ and https://help.napkin.ai/', 'YouTube search: Gamma Napkin AI presentation tutorial Urdu Hindi', 'Project: Turn a one-page business proposal into a ten-slide pitch deck and three process visuals, then manually correct claims and visual hierarchy.'),
    (13, 'CapCut Free, Clipchamp and Whisper: Video and Transcription', 'Official guides: https://www.capcut.com/resource and https://github.com/openai/whisper', 'YouTube search: CapCut AI Whisper transcription Urdu Hindi', 'Project: Produce a 60-second vertical promotional video with script, captions, noise cleanup, B-roll plan, thumbnail and transcript.'),
    (14, 'Google Forms, Tally and Sheets: Structured Data Collection', 'Official guides: https://support.google.com/docs/topic/9055404 and https://tally.so/help', 'YouTube search: Google Forms Tally Google Sheets automation Urdu Hindi', 'Project: Build a client intake form connected to a clean lead sheet with validation, status columns, duplicate detection and an automated response template.'),
    (15, 'Google Apps Script: Free Workspace Automation', 'Official guide: https://developers.google.com/apps-script/guides', 'YouTube search: Google Apps Script automation course Urdu Hindi', 'Project: Automate form-to-email follow-up, generate a Google Doc from each approved row and log every execution with error handling.'),
    (16, 'Zapier Free: Triggers, Actions and Two-Step Automations', 'Official guide: https://help.zapier.com/hc/en-us/articles/8496288690317', 'YouTube search: Zapier free automation tutorial Urdu Hindi', 'Project: Build and document three free two-step Zaps for lead capture, task notification and file logging; include test data and failure scenarios.'),
    (17, 'Make Free: Visual Scenarios, Routers and Data Mapping', 'Official guide: https://help.make.com/', 'YouTube search: Make.com automation complete course Urdu Hindi', 'Project: Create a visual lead-routing scenario that validates inputs, branches by service, updates a sheet and sends a personalized acknowledgement.'),
    (18, 'Pipedream Free: APIs, Webhooks and Lightweight Code', 'Official guide: https://pipedream.com/docs/workflows/', 'YouTube search: Pipedream webhook API automation Urdu Hindi', 'Project: Build a webhook workflow that cleans JSON, calls a public API, stores the result and sends an error alert without exposing secrets.'),
    (19, 'n8n Self-Hosted: Core Nodes and Business Workflows', 'Official guide: https://docs.n8n.io/try-it-out/quickstart/', 'YouTube search: n8n self hosted complete course Urdu Hindi', 'Project: Run n8n locally and build a multi-step inquiry pipeline using webhook, validation, Google Sheets, email and execution logs.'),
    (20, 'n8n AI Workflows: Models, Memory, Tools and Human Approval', 'Official guide: https://docs.n8n.io/advanced-ai/', 'YouTube search: n8n AI agent workflow Urdu Hindi', 'Project: Create a support-draft agent that searches a knowledge base, proposes an answer and requires human approval before any message is sent.'),
    (21, 'Activepieces Open Source: Free No-Code Automation', 'Official guide: https://www.activepieces.com/docs', 'YouTube search: Activepieces AI automation Urdu Hindi', 'Project: Self-host Activepieces or use its free tier to automate content approval across a form, table, AI step and notification channel.'),
    (22, 'Flowise Open Source: Visual LLM Apps and RAG', 'Official guide: https://docs.flowiseai.com/', 'YouTube search: Flowise RAG chatbot tutorial Urdu Hindi', 'Project: Build a source-grounded company-policy chatbot with document ingestion, citations, fallback response and an embeddable chat interface.'),
    (23, 'Langflow Open Source: Components, Tools and Agent Flows', 'Official guide: https://docs.langflow.org/', 'YouTube search: Langflow AI agent tutorial Urdu Hindi', 'Project: Build a research assistant flow that accepts a topic, uses approved tools, creates structured findings and exports a referenced brief.'),
    (24, 'Dify Open Source: AI Apps, Knowledge Bases and Workflows', 'Official guide: https://docs.dify.ai/', 'YouTube search: Dify AI workflow knowledge base Urdu Hindi', 'Project: Create a product advisor with a knowledge base, conditional workflow, conversation variables, testing dataset and public demo page.'),
    (25, 'Botpress Free Tier: Customer-Service Chatbot Automation', 'Official guide: https://botpress.com/docs', 'YouTube search: Botpress chatbot complete course Urdu Hindi', 'Project: Build a bilingual FAQ and lead-capture chatbot with validation, escalation to a human and transcript logging.'),
    (26, 'APIs, Webhooks, JSON and Authentication for No-Code Builders', 'Official learning resource: https://developer.mozilla.org/en-US/docs/Web/HTTP and https://webhook.site/', 'YouTube search: API webhook JSON for beginners Urdu Hindi', 'Project: Connect a free public API to n8n, Make or Pipedream; handle authentication, pagination, rate limits, invalid data and retries.'),
    (27, 'Reliable Automation: Filters, Retries, Logging and Alerts', 'Official guide: https://docs.n8n.io/flow-logic/error-handling/', 'YouTube search: automation error handling retries logging Urdu Hindi', 'Project: Upgrade an earlier workflow with idempotency, duplicate prevention, retry/backoff, failure alerts, audit logs and a manual recovery path.'),
    (28, 'AI Safety: Prompt Injection, PII, Permissions and Cost Controls', 'Official guide: https://genai.owasp.org/llm-top-10/', 'YouTube search: AI automation security prompt injection Urdu Hindi', 'Project: Threat-model one AI workflow, redact personal data, restrict tool permissions, add input/output guardrails and run ten adversarial tests.'),
    (29, 'Freelance Automation Packages, Documentation and ROI', 'Official reference: https://www.notion.so/help/guides and https://www.loom.com/blog/category/how-to', 'YouTube search: sell AI automation services Fiverr Upwork Urdu Hindi', 'Project: Create Starter, Growth and Advanced service packages with scope, architecture diagram, SOP, demo video, maintenance plan and ROI calculator.'),
    (30, 'Final Capstone: AI-Powered Automated Business Operations Hub', 'Use the official documentation referenced throughout Days 1-29.', 'YouTube search: complete AI business automation capstone Urdu Hindi', 'Capstone: Build and present an end-to-end system for a real/local business covering lead intake, AI qualification, CRM sheet, knowledge assistant, content generation, approval, follow-up, dashboard, security, logs and recovery. Submit workflow exports, documentation, test evidence and demo video.')
)
insert into public.course_topics (course_id, day_number, title, english_video, urdu_video, practice_project)
select selected_course.id, rows.day_number, rows.title, rows.english_video, rows.urdu_video, rows.practice_project
from selected_course cross join rows
on conflict (course_id, day_number) do update set
  title = excluded.title,
  english_video = excluded.english_video,
  urdu_video = excluded.urdu_video,
  practice_project = excluded.practice_project;

commit;
