create table if not exists public.student_activity_daily (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  activity_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  active_seconds integer not null default 0 check (active_seconds >= 0),
  page_views integer not null default 0 check (page_views >= 0),
  submit_actions integer not null default 0 check (submit_actions >= 0),
  unique (student_id, activity_date)
);

create table if not exists public.student_activity_events (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null check (event_type in ('page_view', 'submit')),
  path text not null,
  label text,
  occurred_at timestamptz not null default now()
);

create index if not exists student_activity_daily_date_idx on public.student_activity_daily(activity_date desc);
create index if not exists student_activity_events_student_time_idx on public.student_activity_events(student_id, occurred_at desc);

alter table public.student_activity_daily enable row level security;
alter table public.student_activity_events enable row level security;

create or replace function public.record_student_activity(
  p_event_type text,
  p_path text,
  p_label text default null,
  p_active_seconds integer default 0
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_id uuid := auth.uid();
  v_today date := (now() at time zone 'Asia/Karachi')::date;
  v_seconds integer := greatest(0, least(coalesce(p_active_seconds, 0), 60));
  v_page_views integer := case when p_event_type = 'page_view' then 1 else 0 end;
  v_submits integer := case when p_event_type = 'submit' then 1 else 0 end;
begin
  if v_student_id is null or not exists (
    select 1 from public.profiles where id = v_student_id and role = 'student' and status = 'approved'
  ) then
    raise exception 'Only approved students can record activity';
  end if;

  if p_event_type not in ('page_view', 'submit', 'heartbeat') then
    raise exception 'Unsupported activity type';
  end if;

  insert into public.student_activity_daily (
    student_id, activity_date, first_seen_at, last_seen_at, active_seconds, page_views, submit_actions
  ) values (
    v_student_id, v_today, now(), now(), v_seconds, v_page_views, v_submits
  )
  on conflict (student_id, activity_date) do update set
    last_seen_at = now(),
    active_seconds = student_activity_daily.active_seconds + excluded.active_seconds,
    page_views = student_activity_daily.page_views + excluded.page_views,
    submit_actions = student_activity_daily.submit_actions + excluded.submit_actions;

  if p_event_type in ('page_view', 'submit') then
    insert into public.student_activity_events(student_id, event_type, path, label)
    values (v_student_id, p_event_type, left(coalesce(p_path, '/student'), 500), left(nullif(trim(p_label), ''), 500));
  end if;
end;
$$;

revoke all on function public.record_student_activity(text, text, text, integer) from public;
grant execute on function public.record_student_activity(text, text, text, integer) to authenticated;

